cloud-bulldozer/benchmark-operator

test.sh
test_crs/valid_uperf.yaml

Added simple smoke test for CI

---

CONTRIBUTE.md

Broken link

---

docs/sysbench.md
docs/uperf.md
roles/fio-bench/tasks/main.yml
roles/sysbench/tasks/main.yml
roles/uperf-bench/tasks/main.yml
test.sh
tests/common.sh
tests/test_fio.sh
tests/test_sysbench.sh
tests/test_uperf.sh

Also updated tests to look for job completion.
uperf: clients and fio both don't need to be running forever, so switched to jobs

Using kind:jobs for uperf/fio

---

resources/crds/bench_v1alpha1_bench_cr.yaml

set sysbench to disabled in example cr

---

build/Dockerfile

This version is necessary to work with KNI/RHHI.

New version of ansible-operator

---

CONTRIBUTE.md
deploy/role.yaml
docs/couchbase.md
docs/installation.md
docs/sysbench.md
docs/uperf.md
docs/ycsb.md
resources/crds/benchmark_v1alpha1_benchmark_cr.yaml
resources/crds/benchmark_v1alpha1_benchmark_crd.yaml
roles/fio-bench/README.md
roles/fio-bench/tasks/main.yml
roles/uperf-bench/README.md
roles/uperf-bench/tasks/main.yml
tests/common.sh
tests/test_crs/valid_couchbase.yaml
tests/test_crs/valid_fio.yaml
tests/test_crs/valid_sysbench.yaml
tests/test_crs/valid_uperf.yaml
tests/test_crs/valid_ycsb-couchbase.yaml
tests/test_fio.sh
watches.yaml

Moving our resource to benchmark from bench.

Migrating to benchmark

---

roles/fio-bench/tasks/main.yml
roles/sysbench/templates/workload.yml
roles/uperf-bench/tasks/main.yml

Move workload images to shared namespace

Remove images from personal repos

---

docs/installation.md
docs/uperf.md
resources/operator_store_results.yaml
resources/result-pvc.yaml
roles/result/tasks/main.yml
roles/result/templates/result.json
roles/uperf-bench/tasks/main.yml
roles/uperf-bench/templates/workload.yml.j2
roles/uperf-bench/templates/workload_store.yml.j2
tests/test_crs/valid_uperf_store.yaml

- Added new role result which will upload base64 encoded data to es
- Currently only uperf supports it
Closes #26
Co-authored-by: Joe (rook) <joe.talerico@gmail.com>

Upload uperf results

---

docs/uperf.md
resources/crds/benchmark_v1alpha1_uperf_cr.yaml
roles/uperf-bench/tasks/main.yml
roles/uperf-bench/templates/server.yml.j2
roles/uperf-bench/templates/uperf-test.xml.j2
roles/uperf-bench/templates/workload.yml.j2
roles/uperf-bench/templates/workload_store.yml.j2
tests/test_crs/valid_uperf.yaml
tests/test_crs/valid_uperf_store.yaml

Allow for :
- hostNetwork testing -- not using OpenShift SDN
- Pods to be scheduled to specific nodes using hostname

Add support for more network scenarios

---

roles/uperf-bench/tasks/main.yml
roles/uperf-bench/templates/workload.yml.j2
roles/uperf-bench/templates/workload_store.yml.j2

The jinja loop was causing issues with YAML templating. Removing this
for now.

Remove loop in jinja

---

workloads/sysbench-Dockerfile

Adding the missing sysbench workload dockerfile

sysbench workload missing

---

playbook.yml
roles/uuid/tasks/main.yml

Useful when storing/indexing results from running workloads.

Adding logic to generate UUID

---

CONTRIBUTE.md
roles/fio-bench/tasks/main.yml
roles/fio-distributed/templates/client.yaml
roles/fio-distributed/templates/servers.yaml
roles/iperf3-bench/templates/client.yml.j2
roles/iperf3-bench/templates/client_store.yml.j2
roles/iperf3-bench/templates/server.yml.j2
roles/sysbench/templates/workload.yml
roles/uperf-bench/templates/server.yml.j2
roles/uperf-bench/templates/workload.yml.j2
roles/uperf-bench/templates/workload_store.yml.j2
roles/ycsb-bench/tasks/main.yml
workloads/fio-Dockerfile
workloads/iperf-Dockerfile
workloads/sysbench-Dockerfile
workloads/uperf-Dockerfile
workloads/ycsb-Dockerfile

Updated documentation the same as well.

Moving Dockerfiles to magazine

---

test.sh
tests/common.sh
tests/test_list

Iterate over tests/test_list as well as cleanup/re-deploy the deploy and operator.yaml files for each CI test. This will always run all the tests and give a summary. If any fail it will be marked with a failure.

Iterate over test_list for all ci tests

---

test.sh
tests/common.sh
tests/full_test_file_trigger

To ensure that a specific test is ran only if the roles directory is changed.
And run all the tests if higher level files/dirs are changed, which are stored
in tests/full_test_file_trigger

selectively running tests

---

test.sh
tests/common.sh
tests/full_test_file_trigger

Reverts cloud-bulldozer/ripsaw#132

Revert "selectively running tests"

---

resources/crds/ripsaw_v1alpha1_byowl_cr.yaml
resources/crds/ripsaw_v1alpha1_fio_cr.yaml

Cosmetic CR issue

---

roles/uperf-bench/tasks/main.yml

remove repeated tasks from roles/uperf-bench/tasks/main.yml

---

docs/fio_distributed.md
resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
roles/fio-distributed/tasks/main.yml
roles/fio-distributed/templates/client.yaml
roles/fio-distributed/templates/client_store.yaml
roles/pre-result/tasks/fiod.yml
roles/result/tasks/fiod-clat-hist.yaml
roles/result/tasks/fiod-samples.yml
roles/result/tasks/fiod.yaml
roles/result/templates/fiod.json.j2
roles/result/templates/fiod_bw.json.j2
roles/result/templates/fiod_clat.json.j2
roles/result/templates/fiod_clat_hist.json.j2
roles/result/templates/fiod_iops.json.j2
roles/result/templates/fiod_lat.json.j2
roles/result/templates/fiod_slat.json.j2
tests/test_crs/valid_fiod.yaml
tests/test_crs/valid_fiod_store.yaml
tests/test_fiod.sh

runnning/indexing with 2 samples - http://marquez.perf.lab.eng.rdu2.redhat.com:5601/goto/855d7859a84278374ed87c5cbe124076

Fio-distributed running multiple samples

---

resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml

Show benchmark type when getting Benchmark CRs from kubectl

Show benchmark type

---

roles/pgbench/templates/workload.yml.j2

fix jinja2 if logic for pin_node feature of pgbench workload

---

full_test.sh
test.sh
tests/common.sh

Reverts cloud-bulldozer/ripsaw#148

Revert "Fixing testscript"

---

docs/pgbench.md
resources/crds/ripsaw_v1alpha1_pgbench_cr.yaml
roles/pgbench/templates/workload.yml.j2
tests/test_crs/valid_pgbench.yaml

Enhances pgbench to execute via snafu wrapper, allowing indexing to elastic.

integrate snafu wrapper of pgbench for elastic indexing

---

docs/ycsb.md
playbook.yml
resources/crds/ripsaw_v1alpha1_ycsb_cr.yaml
roles/load-ycsb/defaults/main.yml
roles/load-ycsb/tasks/main.yml
roles/load-ycsb/templates/configmap.yml.j2
roles/ycsb-bench/defaults/main.yml
roles/ycsb-bench/templates/configmap.yml.j2
tests/test_crs/valid_ycsb-mongo.yaml
tests/test_ycsb.sh

This allows the user to modify the YCSB workload a bit.

Allow user provide more detail to YCSB

---

roles/fio-distributed/templates/client.yaml

Follows merge of https://github.com/cloud-bulldozer/snafu/pull/22

moving sample loop to snafu

---

docs/fio_distributed.md
docs/pgbench.md
docs/uperf.md
docs/ycsb.md
group_vars/all.yml
resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
resources/crds/ripsaw_v1alpha1_pgbench_cr.yaml
resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
resources/crds/ripsaw_v1alpha1_uperf_index_cr.yaml
resources/crds/ripsaw_v1alpha1_ycsb_cr.yaml
roles/fio-distributed/templates/client.yaml
roles/load-ycsb/tasks/main.yml
roles/pgbench/templates/workload.yml.j2
roles/uperf-bench/templates/workload.yml.j2
roles/ycsb-bench/tasks/main.yml

Follows https://github.com/cloud-bulldozer/snafu/pull/34/files

Adding clustername var to roles that index benchmark results

---

build/Dockerfile
deploy/20_role.yaml
resources/operator.yaml

This will allow us to use the log sidecart to get better logging output.

Updating to latest operator framework

---

roles/fio-distributed/tasks/main.yml

I missed FIOD when I was reconciling the world. This is to fix that

FIOD was missed

---

roles/smallfile-bench/templates/workload_job.yml.j2

Simple fix, that would drive someone with OCD nuts.

Fixing Smallfile case

---

CHANGELOG.md
docs/installation.md
resources/operator.yaml
roles/fio-distributed/templates/client.yaml
roles/fio-distributed/templates/servers.yaml
roles/fs-drift/tasks/main.yml
roles/fs-drift/templates/workload_job.yml.j2
roles/iperf3-bench/templates/client.yml.j2
roles/iperf3-bench/templates/client_store.yml.j2
roles/iperf3-bench/templates/server.yml.j2
roles/load-ycsb/tasks/main.yml
roles/pgbench/defaults/main.yml
roles/smallfile-bench/tasks/main.yml
roles/smallfile-bench/templates/workload_job.yml.j2
roles/sysbench/templates/workload.yml
roles/uperf-bench/templates/server.yml.j2
roles/uperf-bench/templates/workload.yml.j2
roles/ycsb-bench/tasks/main.yml

This is the first test release. 
NOTE: not that this is 0.0.1, so not a release we'll be looking to publish.

cutting 0.0.1 release

---

roles/fio-distributed/templates/client.yaml

This is essentially the PR #204

updating fio to use run_snafu

---

tests/common.sh

At times uploading an image to quay can result in errors. This adds 2 additional retries as well as an exit in case the upload fails.

Add retry and failure when pushing image to quay

---

resources/crds/ripsaw_v1alpha1_fs_drift_cr.yaml
roles/fs-drift/templates/workload_job.yml.j2
tests/common.sh
tests/test_fs_drift.sh

do not merge or test this PR without snafu PR 51.
It simply calls run_snafu.  I removed some cruft that was no longer needed.

use run_snafu.py for fs-drift

---

resources/crds/ripsaw_v1alpha1_ycsb_cr.yaml

fixed typo in ripsaw_v1alpha1_ycsb_cr.yaml

fixed typo in ripsaw_v1alpha1_ycsb_cr.yaml

---

roles/ycsb-bench/tasks/main.yml

ycsb.options_load was used for both run and load phase, possible copy pasta error. fixing it

BUG: ycsb options_run not used for run phase

---

playbook.yml

Fixing for a case where the state may be undefined

Bugfix in playbook.yml

---

README.md
deploy/20_role.yaml
docs/uperf.md
resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
resources/crds/ripsaw_v1alpha1_uperf_vm.yaml
roles/uperf-bench/tasks/main.yml
roles/uperf-bench/templates/configmap_script.yml.j2
roles/uperf-bench/templates/server_vm.yml.j2
roles/uperf-bench/templates/workload.yml.j2
roles/uperf-bench/templates/workload_vm.yml.j2
tests/test_crs/valid_uperf.yaml

This will allow Ripsaw to orchestrate Uperf on VMs.
please note: I'm not gonna add a CI until kubevirt/cnv stabilizes - rn we're hitting oom and all sorts of problems while the job itself would take more than the current test suite run time as for some reason custom container-disk-images only seem to work on kubevirt without any issue

Uperf on VMinstances

---

roles/uperf-bench/templates/workload.yml.j2

This will export client_node and server_node for indexing when the 'pin' is set to true. If it is set to false it will export the string "UNSET" @jtaleric

Add client_node and server_node metadata

---

docs/metadata.md
resources/backpack_role.yaml

Minor updates to metadata documentation

metadata docs update

---

roles/uperf-bench/templates/service.yml.j2

This change will sync up with the change in https://github.com/cloud-bulldozer/ripsaw/blob/d24383b53d27b0106b4f5b2114c96aa9929f0a9b/roles/uperf-bench/templates/server.yml.j2#L8
@aakarshg 
Closes #256

Add UUID to the label

---

tests/test_crs/valid_smallfile.yaml
tests/test_smallfile.sh

Required for https://github.com/cloud-bulldozer/snafu/pull/102. @aakarshg

Test multiple clients in parallel

---

tests/test_pgbench.sh

Updating to apps/v1 and adding the now required selector

Updating Deployment to apps/v1

---

tests/common.sh

Exit on operator build error to improve CI reliability

Exit on operator build error

---

roles/uperf-bench/tasks/main.yml
tests/test_crs/valid_uperf_serviceip.yaml
tests/test_uperf.sh

Moving the ServiceIP Capture

---

test.sh
tests/common.sh

This has ci now only run tests related to the change. However, if some critical files are changed it will run all the tests.

Updating ci test scripts to run tests related to the change

---

roles/load-ycsb/defaults/main.yml
roles/load-ycsb/tasks/main.yml
roles/ycsb-bench/defaults/main.yml
roles/ycsb-bench/tasks/main.yml

Dependent on - [PR #139 snafu](https://github.com/cloud-bulldozer/snafu/pull/139)

Updated ci test for ycsb to support --tool migration

---

roles/hammerdb/defaults/main.yml
roles/hammerdb/templates/db_workload.yml.j2

Using snafu's run_snafu for hammerdb

updated ci for hammerdb to support run_snafu --tool

---

test.sh
tests/common.sh

Added a check for changes in the ci cr files in tests/test_crs/. Additionally, I added a clean exit when no tests are found to need to be run.

Adding ci check for changes in cr files and a clean exit when no test

---

roles/fio-distributed/templates/configmap.yml.j2

This reverts commit 2c492c1342e725a1e93bb5cc710135fa249f3e7e.

Revert "fix fiojob for fio-3.19"

---

tests/common.sh
tests/test_crs/valid_fs_drift_hostpath.yaml

following #299 which increased the duration for normal test

fixing fsdrift hostpath cr

---

roles/uperf-bench/defaults/main.yml
roles/uperf-bench/templates/workload.yml.j2

Dependent on - [PR #138 snafu](https://github.com/cloud-bulldozer/snafu/pull/138)

Updated ci test for uperf to support --tool migration

---

roles/smallfile-bench/tasks/main.yml

Allow customizing smallfile publisher image

Allow customizing smallfile publisher image

---

README.md
roles/hammerdb/tasks/main.yaml

Updated hammerdb to use the reconciliation loop.

Update hammerdb workload to support reconciliation loop

---

test.sh
tests/common.sh
tests/test_crs/valid_backpack.yaml
tests/test_crs/valid_byowl.yaml
tests/test_crs/valid_fiod.yaml
tests/test_crs/valid_fiod_hostpath.yaml
tests/test_crs/valid_fs_drift.yaml
tests/test_crs/valid_fs_drift_hostpath.yaml
tests/test_crs/valid_hammerdb.yaml
tests/test_crs/valid_iperf3.yaml
tests/test_crs/valid_pgbench.yaml
tests/test_crs/valid_smallfile.yaml
tests/test_crs/valid_smallfile_hostpath.yaml
tests/test_crs/valid_sysbench.yaml
tests/test_crs/valid_uperf.yaml
tests/test_crs/valid_uperf_resources.yaml
tests/test_crs/valid_uperf_serviceip.yaml
tests/test_crs/valid_uperf_store.yaml
tests/test_crs/valid_ycsb-mongo.yaml

Updating some variables and information for the new CI environment

Updating for new ci environment

---

test.sh

Allow passing of max concurrent (parallel), choice of tests, ES server and ES port to test.sh. Omitting the arguments sets them to defaults
Example to set max parallel to 1
```
```
Example to set max parallel to 2 and only run the hammerdb and fs-drift tests
```
```
Example to set ES server to foo and ES port to 90
```
```
This allows the user to still simulate all the work done in the CI environment while targeting specific tests. This will also enable us to potentially take tests as command line flags to /rerun when triggering a rerun of a PR.

Allow passing of additional arguments to test.sh

---

roles/vegeta/templates/vegeta.yml.j2

Move to using the Vegeta installed via pip

Use pip installed Vegeta

---

resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
resources/crds/ripsaw_v1alpha1_fio_distributed_vm_cr.yaml
roles/fio_distributed/tasks/main.yml
roles/fio_distributed/templates/configmap.yml.j2

Several items:
* Wait for fio server VMs to be up before starting fio tests
* Fix blocksizes in example CRs - solves issues for me

Fio enhancements

---

README.md
docs/elastic.md
docs/prometheus.md
resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
roles/fio_distributed/templates/client.yaml
roles/fs-drift/templates/workload_job.yml.j2
roles/hammerdb/templates/db_workload.yml.j2
roles/pgbench/templates/workload.yml.j2
roles/smallfile/templates/workload_job.yml.j2
roles/uperf/templates/workload.yml.j2
roles/vegeta/templates/vegeta.yml.j2
roles/ycsb/templates/ycsb_load.yaml
roles/ycsb/templates/ycsb_run.yaml

This PR adds variables to be used in snafu for passing prometheus ES variables. This also adds the parallel variable to elasticsearch.

Allow passing of prometheus elasticsearch information 

---

roles/fio_distributed/templates/client.yaml

fixed client.yaml to handle bsrange variable

fixed client.yaml to handle bsrange variable

---

tests/test_crs/valid_fiod_bsrange.yaml
tests/test_fiod.sh

added ci test for a valid fiod test using bsrange

added ci test for a valid fiod test using bsrange

---

tests/test_crs/valid_fiod_bsrange.yaml

changed bsvalue from static bs to range 4k-16k

changed bsvalue from static bs to range 4k-16k

---

docs/cache_dropping.md

Not every benchmark can do this, only the ones that pass 2 env vars to run_snafu.py, currently that is fio_distributed.   Also, nodes must be labeled with kernel-cache-dropper key and a piece of RBAC specific to kernel cache dropper must be executed.

add additional missing steps for cache dropping to doc

---

resources/crds/ripsaw_v1alpha1_stressng_cr.yaml

Fix typo in stressng crd

---

roles/uperf/templates/server_vm.yml.j2
roles/uperf/templates/workload_vm.yml.j2

Installs required git command in uperf VMs.
Fixes #429 

Installing git in uperf VMs

---

roles/kube-burner/files/metrics-aggregated.yaml
roles/kube-burner/files/metrics.yaml

Adding the etcd guru's goto prom queries to our collection
Fixes #455

Adding hexfusion's recommendations

---

roles/kube-burner/files/metrics-aggregated.yaml
roles/kube-burner/files/metrics.yaml

s/container_fs_writes_total/container_fs_writes_bytes_total/g
We're not sure what unit represents fs_writes_total

Container IO metrics

---

README.md
docs/cyclictest.md
docs/installation.md
resources/crds/ripsaw_v1alpha1_cyclictest_cr.yaml
roles/cyclictest/files/cyclictest.sh
roles/cyclictest/files/functions.sh
roles/cyclictest/tasks/main.yml
roles/cyclictest/templates/cyclictestjob.yaml

Add cyclictest workload for RT performance

---

docs/cache_dropping.md
docs/scale_openshift.md
docs/uperf.md

I noticed a few small documentation mistakes and fixed them.

Add documentation fixes

---

roles/kube-burner/templates/cluster-density.yml.j2
roles/kube-burner/templates/kubelet-density-heavy.yml.j2
roles/kube-burner/templates/kubelet-density.yml.j2

Useful to run several iterations in different namespaces.

Append uuid to namespace name

---

docs/cache_dropping.md
roles/smallfile/templates/workload_job.yml.j2
tests/test_smallfile.sh

uses benchmark-wrapper PR 225 
Tested in minikube v1.11.0

Smallfile cachedrop

---

README.md
docs/installation.md
docs/oslat.md
resources/crds/ripsaw_v1alpha1_oslat_cr.yaml
roles/oslat/files/functions.sh
roles/oslat/files/oslat.sh
roles/oslat/tasks/main.yml
roles/oslat/templates/oslatjob.yaml

Add oslat workload for realtime latency

---

deploy/20_role.yaml
docs/uperf.md
playbook.yml
resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
resources/crds/ripsaw_v1alpha1_uperf_vm.yaml
roles/common/tasks/main.yml
roles/common/templates/networkpolicy.yml.j2
roles/uperf/templates/workload.yml.j2
roles/uperf/templates/workload_vm.yml.j2
tests/test_crs/valid_uperf_networkpolicy.yaml
tests/test_uperf.sh

Enable simple NetworkPolicy

---

roles/stressng/templates/jobfile.j2
roles/stressng/templates/stressng_workload.yml.j2

Allow running stressors optionally

---

roles/uperf/templates/workload.yml.j2

Fix for issue 485 - uperf with multus not working

---

roles/kube-burner/files/metrics-aggregated.yaml
roles/kube-burner/files/metrics.yaml

These etcd metrics are interesting and might help to detect some regressions.

Add roundtrip and database etcd metrics

---

roles/uperf/templates/workload.yml.j2

Export networkpolicy state for consumption in wrapper

---

roles/kube-burner/tasks/main.yml

Remove duplicated task

---

docs/kube-burner.md
roles/kube-burner/templates/kube-burner.yml.j2

Integrate Kube-burner alerting using remote configuration files.

Kube-burner alerting

---

docs/elastic.md

- Fixed typo in elastic.md for ES server - server -> url change

- Fixed typo in elastic.md for ES server - server -> url change

---

deploy/25_role.yaml
deploy/35_role_binding.yaml
tests/common.sh
watches.yaml

Effort to disable automatic snake_case conversion in operator-sdk. Reference https://sdk.operatorframework.io/docs/building-operators/ansible/reference/watches/
Can help fixing the issues found at https://github.com/cloud-bulldozer/benchmark-operator/issues/533

Disable snake_case conversion

---

charts/benchmark-operator/README.md
charts/benchmark-operator/templates/operator.yaml
charts/benchmark-operator/values.yaml

This adds a new variable to values.yaml named redisImage.
Specifying a custom location for the image can be needed in secure
environments.

Make redis image a variable

---

roles/kube-burner/templates/kube-burner.yml.j2

Fixes running kube-burner w/o indexing

Make es_url parameter optional

---

docs/log_generator.md
roles/log_generator/tasks/main.yml
roles/log_generator/templates/log_generator.yml

Add support for kafka as log backend for verification

---

docs/cerberus.md

Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
Addressing comment from @chaitanyaenr here https://github.com/cloud-bulldozer/benchmark-operator/pull/572#discussion_r630498137

Expand README

---

docs/testpmd.md
roles/testpmd/templates/trex.yml.j2

1. Altered syntax for command args, to fix #576 
2. Helps to run TRex on Mellanox [ConnectX-5] VFs

Trex template change 

---

docs/log_generator.md
roles/log_generator/templates/log_generator.yml

Make sink verification optional for kafka

---

resources/crds/ripsaw_v1alpha1_stressng_vm.yaml
roles/stressng/templates/stressng_workload.yml.j2
roles/stressng/templates/stressng_workload_vm.yml.j2

Add ElasticSearch support
Add the following:
Pod: stressng
1. nodeselector 
2. 2. resources requests/limits
VM: stressng
1. Add ElasticSearch support
2. Change pip3 to pip

add stressng vm elasticsearch/nodeselector support

---

roles/kube-burner/files/metrics-aggregated.yaml
roles/kube-burner/files/metrics.yaml

add alerts to kube-burner dash

add alerts to kube-burner dash

---

max-namespaces.yml
roles/kube-burner/files/metrics-aggregated.yaml
roles/kube-burner/files/metrics.yaml

Metric profiles have now a new structure: https://github.com/cloud-bulldozer/kube-burner/pull/89

Update metric profiles to new schema

---

roles/kube-burner/files/metrics-aggregated.yaml
roles/kube-burner/files/metrics.yaml

Add cri-o network setup latency metrics

---

roles/kube-burner/files/metrics-aggregated.yaml
roles/kube-burner/files/metrics.yaml

We need more granularity in tests like node-density

Add container granurality to metrics

---

docs/kube-burner.md
roles/kube-burner/tasks/main.yml
roles/kube-burner/templates/kube-burner.yml.j2

Mechanism to inject arbitrary env vars to the kube-burner benchmark.

Arbitrary env vars to kube-burner

---

docs/kube-burner.md
roles/kube-burner/templates/kube-burner.yml.j2

Extra env vars as dictionary rather than a list of dictionaries

---

roles/kube-burner/files/case2-networkpolicy.yaml
roles/kube-burner/files/case3-networkpolicy.yaml
roles/kube-burner/files/cross-ns-networkpolicy.yaml
roles/kube-burner/files/networkpolicy-deny-all.yaml
roles/kube-burner/files/networkpolicy-ingress.yaml
roles/kube-burner/files/networkpolicy-monitoring.yaml
roles/kube-burner/files/networkpolicy-same-ns.yaml
roles/kube-burner/files/nginx-cross-ns.yaml
roles/kube-burner/files/nginx.yaml
roles/kube-burner/tasks/main.yml
roles/kube-burner/templates/networkpolicy-case2.yml.j2
roles/kube-burner/templates/networkpolicy-case3.yml.j2
roles/kube-burner/templates/networkpolicy-cross-ns.yml.j2
roles/kube-burner/templates/networkpolicy-multitenant.yml.j2

Cases are explained here https://docs.google.com/document/d/1OQtOXtqqHzV79vJ04r3z1icv5b-9y5AtWGrEgUMnvEg/edit

add networkpolicy cases for kube-burner

---

docs/cyclictest.md
docs/fio_distributed.md
docs/flent.md
docs/fs-drift.md
docs/hammerdb.md
docs/iperf.md
docs/kube-burner.md
docs/oslat.md
docs/pgbench.md
docs/servicemesh.md
docs/smallfile.md
docs/stressng.md
docs/sysbench.md
docs/uperf.md
docs/vegeta.md
docs/ycsb.md

Fix broken links in majority of the workload docs
@whitleykeith

Fix broken links in the docs

---

roles/stressng/templates/stressng_workload_vm.yml.j2

Add vm completed state for stressng
stressng_workload_vm.yml.j2 - add completed state

Stressng: add vm completed state

---

roles/hammerdb/templates/db_creation_mariadb_vm.yml
roles/hammerdb/templates/db_creation_mssql_vm.yml
roles/hammerdb/templates/db_creation_postgres_vm.yml
roles/hammerdb/templates/db_mariadb_workload_vm.sh.j2
roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
roles/hammerdb/templates/db_postgres_workload_vm.sh.j2

Hammerdb vm completed
Add redis completed status support for VM

Hammerdb vm completed

---

tests/common.sh

This if statement is causing https://github.com/cloud-bulldozer/benchmark-operator/pull/627 to fail. Removing as it is unclear the purpose of it and it was not there pre-version upgrade.

remove if from populate_test_list function

---

Makefile

make undeploy needs kustomize; the undeploy target should depend on it.

make undeploy should depend on make kustomize

---

config/samples/fio/cr.yaml
config/samples/fio/vm-cr.yaml
docs/fio_distributed.md

update fio documentation, particularly with respect to cache dropping and job_timeout

Fio doc fixes

---

roles/oslat/templates/oslatjob.yaml

Fix oslat execution

---

roles/testpmd/tasks/main.yml
roles/testpmd/templates/testpmd.yml.j2

Since Testpmd  is the server side of the workload, it must be a Pod rather than a Job if we want the benchmark to be set as complete after the workload finishes

Convert testpmd into pod

---

config/samples/smallfile/cr.yaml
docs/smallfile.md
roles/smallfile/templates/smallfilejob.other_parameters.yaml.j2
roles/smallfile/templates/workload_job.yml.j2
tests/test_crs/valid_smallfile.yaml

do not merge yet.  add smallfile auto-pause parameter, plus passing all parameters from CR through to smallfile.
part of the fix for issue #595

Smallfile cr params

---

roles/cyclictest/templates/cyclictestjob.yaml

cyclictest didn't even start, removing the backslashes fixes this issue
non-start of cyclictest

fixed cyclictest execution

---

docs/scale_openshift.md
roles/scale_openshift/templates/scale.yml

Add rosa parameters on snafu execution if they are detected as workload arguments
Adding also aws parameters also as workload arguments as they are required by rosa to run scaling process

add rosa parameters to scale template

---

roles/vegeta/templates/vegeta.yml.j2
tests/test_crs/valid_vegeta.yaml

Vegeta pod synchronization does not work correctly, CI test sometimes fails. This PR improves and simplifes the way those pods are synchronized.
Fixes flacky vegeta test

Improve vegeta synchronization

---

docs/e2e-ci.md
docs/kube-burner.md
e2e/008-kube-burner.bats
e2e/kube-burner/concurrent-builds.yaml
e2e/kube-burner/configmap-cfg.yaml
e2e/kube-burner/configmap.yaml
e2e/kube-burner/max-namespaces.yaml
e2e/kube-burner/max-services.yaml
e2e/kube-burner/node-density-heavy.yaml
e2e/kube-burner/node-density.yaml
roles/kube-burner/tasks/main.yml
roles/kube-burner/templates/kube-burner.yml.j2

With this PR the kube-burner benchmark will be able to read its own configuration from configmaps in the same namespace where is running.

Kube burner configmap config

---

roles/api_load/tasks/main.yml
roles/byowl/tasks/main.yml
roles/generic_workload/tasks/main.yml
roles/image_pull/tasks/main.yml
roles/log_generator/tasks/main.yml
roles/oslat/tasks/main.yml
roles/scale_openshift/tasks/main.yml
roles/vegeta/tasks/main.yml

First approach of the issue described below
- https://github.com/cloud-bulldozer/benchmark-operator/issues/672

Migration to generic_workload

---

roles/hammerdb/templates/db_mariadb_workload_vm.sh.j2
roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
roles/hammerdb/templates/db_postgres_workload_vm.sh.j2

Fix dependency issue by pip upgrade
ImportError: cannot import name 'PROTOCOL_TLS'
After adding 'pip3 install --upgrade pip;' issue was solved
Full error log
`Traceback (most recent call last):
File "/usr/local/bin/run_snafu", line 33, in <module>
sys.exit(load_entry_point('snafu==0.0.1', 'console_scripts', 'run_snafu')())
File "/usr/local/bin/run_snafu", line 25, in importlib_load_entry_point
return next(matches).load()
File "/usr/local/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 194, in load
module = import_module(match.group('module'))
File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
File "<frozen importlib._bootstrap>", line 994, in _gcd_import
File "<frozen …

Hammerdb: add upgrade pip

---

.github/workflows/release.yml

Release pipeline is broken since some days ago

Update package list before installing dependencies

---

roles/kube-burner/files/curl-deployment.yml
roles/kube-burner/files/webserver-deployment.yml

This should help with better scheduling.

Add resource requests to templates for CNI workloads

---

roles/kube-burner/files/curl-deployment.yml

Change readiness probe to startup probe for node-density-cni

---

roles/api_load/templates/api_load.yml

Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>
Adds option to check if ES certs are verified

Adds option to check if ES certs are verified

---

roles/uperf/tasks/start_client.yml
roles/uperf/templates/workload_vm.yml.j2

Updates ConfigMap name after recent changes.
Fixes: #761

Update ConfigMap name for CNV

---

config/manager/manager.yaml

Point to redis multi-arch image to support arm architecture.

Point redis image to multi-arch image on docker.io to support arm architecture

---

roles/uperf/templates/workload.yml.j2

Without this, Grafana visualization doesn't work.

missing env var `num_pairs`

---

docs/uperf-scale.md

Updating docs describing the usage of both uperf and uperf-scale mode code changes.

Updating README.md for uperf-scale mode

---

roles/log_generator/templates/log_generator.yml

typo correction 

---

Dockerfile
playbooks/benchmark.yml
requirements.yml
roles/backpack/tasks/main.yml
roles/common/tasks/main.yml
roles/fio_distributed/tasks/main.yml
roles/hammerdb/tasks/main.yaml
roles/kernel_cache_drop/tasks/main.yml
roles/nighthawk/tasks/main.yml
roles/pgbench/tasks/run_workload.yml
roles/testpmd/tasks/main.yml
roles/uperf-scale/tasks/cleanup.yml
roles/uperf-scale/tasks/setup.yml
roles/uperf-scale/tasks/start_client.yml
roles/uperf-scale/tasks/start_server.yml
roles/uperf-scale/tasks/wait_client_done.yml
roles/uperf-scale/tasks/wait_client_ready.yml
roles/uperf-scale/tasks/wait_server_ready.yml
roles/uperf/tasks/main.yml
roles/ycsb/tasks/main.yml

CNV w/ OpenShift 4.15 was broken. This should fix it.
- Closes #
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.

Fixing BMO for CNV

---

README.md

Added a Youtube Video on how to set up the operator for normal human beings
- Closes #

Add Youtube video for Quickstart

---

image_resources/centos8-appstream.repo
roles/fio_distributed/tasks/main.yml
roles/fio_distributed/templates/server_vm.yml.j2

Some quick fixes to make benchmark-operator able to run fio in virtual machines
- Closes #

Kubevirt fixes

---

Dockerfile
image_resources/centos9-appstream.repo
roles/uperf/tasks/main.yml
roles/uperf/templates/configmap_script.yml.j2
roles/uperf/templates/workload.yml.j2
roles/uperf/templates/workload_vm.yml.j2

- [X ] Bug fix
Update uperf process for pods and VMs
Update base image
Update image to use centos stream 9 appstream
- Closes #
- [X ] I have performed a self-review of my code.
- Create Benchmark to exercise VMs and Pods using uperf role
- Tested against OCP 4.18 w/ CNV 4.18

Update uperf process
