cloud-bulldozer/benchmark-operator

- playbook.yml
include_role should be used in this case for conditional execution
of workloads[1]. If using import_role, the when condition only applies
to each task in the role but not to the import statement[2]. Also, if you
are using import_role, all the variables within the role are available
in this playbook and hence the when condition uses vars from the role
defaults. In the case of include_role, the role is conditionally imported
based on the when statement which is what we want in this case.
Also adding check to see if the workload was defined before continuing more
specific checks into workload parameters. This will prevent undefined var errors
by shortciruting with the and operator
References:
1. https://docs.ansible.com/ansible/latest/modules/include_role_module.html
2. …
> Replace import_role with include_role

- deploy/crds/bench_v1alpha1_bench_cr.yaml
- roles/uperf-bench/tasks/main.yml
- roles/uperf-bench/vars/main.yml
Previously, if I removed the CR and added a new CR, the pods in
terminating state would get picked up. This is to fix that logic issue
> Adding logic for leftover servers

- full_test.sh
- test.sh
- tests/common.sh
- tests/test_fio.sh
- tests/test_uperf.sh
1. Divided test.sh into two:
- test.sh - Functional testing for each workload
- full_test.sh - E2E integration testing of sort where operator will not be redeployed
2. Using kubectl wait mechanism instead of using sleep
> Updated CI testing structure

- deploy/cluster_role_kubevirt.yaml
- resources/crds/bench_v1alpha1_bench_cr.yaml
- roles/sysbench/defaults/main.yml
- roles/sysbench/tasks/main.yml
- roles/sysbench/templates/workload.yml
- roles/sysbench/templates/workload_vm.yml
Instead of defining the job/pod/etc in the task we should create a
template which can easily be modified to support different scenarios.
partially fixes #35
> Sysbench template workload

- docs/couchbase.md
- resources/crds/bench_v1alpha1_bench_cr.yaml
- roles/couchbase-infra/defaults/main.yml
- roles/couchbase-infra/tasks/main.yml
- roles/couchbase-infra/templates/couchbase-cluster.yaml.j2
- roles/couchbase-infra/vars/main.yml
- test.sh
- tests/test_couchbase.sh
- tests/test_crs/valid_couchbase.yaml
For issue #37 
Adding couchbase deployment
make operator and pod versions and urls variables changeable by CR
move default vars to defaults dir
making operator and pod versions and URLs user-configurable
> Better defaults and user modification of defaults through CR

- tests/test_ycsb-couchbase.sh
No more race condition to wait for a pod to enter Ready state.
> Fixed ycsb test script

- build/Dockerfile
- resources/operator.yaml
- resources/operator_store_results.yaml
- tests/common.sh
This commit was built to create a mechanism to sync workloads to run at
the sametime. There was a want to do this with FIO, however FIO might
have a built in mechanism to do this. We feel there is still a good
reason to keep this functionality for workloads that do not have built
in sync.
> Use Redis for backend key/value store

- resources/operator_store_results.yaml
result-data volume was not indented properly in the operator Deployment. I was getting this error:
```
oc create -f resources/operator_store_results.yaml                                                                                                                                                                                                
The Deployment "benchmark-operator" is invalid: spec.template.spec.containers[0].volumeMounts[0].name: Not found: "result-data" 
```
> Indent properly volumes for operator container

- CONTRIBUTE.md
- deploy/20_role.yaml
- docs/byowl.md
- docs/couchbase.md
- docs/fio.md
- docs/fio_distributed.md
- docs/installation.md
- docs/sysbench.md
- docs/uperf.md
- docs/ycsb.md
- resources/crds/ripsaw_v1alpha1_byowl_cr.yaml
- resources/crds/ripsaw_v1alpha1_cb_cr.yaml
- resources/crds/ripsaw_v1alpha1_fio_cr.yaml
- resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- resources/crds/ripsaw_v1alpha1_sysbench_cr.yaml
- resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
- resources/crds/ripsaw_v1alpha1_ycsb-cb_cr.yaml
- roles/result/templates/result.json
- tests/common.sh
- tests/test_crs/valid_byowl.yaml
- tests/test_crs/valid_couchbase.yaml
- tests/test_crs/valid_fio.yaml
- tests/test_crs/valid_fiod.yaml
- tests/test_crs/valid_sysbench.yaml
- tests/test_crs/valid_uperf.yaml
- tests/test_crs/valid_uperf_store.yaml
- tests/test_crs/valid_ycsb-couchbase.yaml
- watches.yaml
rename files to match new ripsaw.cloudbulldozer.io domain
fix names, update docs, and default CRs to on
We own cloudbulldozer.io now!
> change all benchmark.example.com references to ripsaw.cloudbulldozer.io

- tests/common.sh
We'll be using node name as a tag while pushing/pulling quay images
for CI, which would be replaced by node_name.
closes #60
> Using node name as tag for CI

- docs/installation.md
Updated change directory command to correct ripsaw directory from benchmark-operator in the installation docs subsection "Deploying operator"
> Documentation reference to incorrect directory

- CONTRIBUTE.md
- resources/operator.yaml
- resources/operator_store_results.yaml
- tests/common.sh
Moving to use quay.io trigger for git push, this would mean that the tag
will be updated to branch name.
Also updated documentation and operator definition to pull from master tag.
> Updating image tag to master

- roles/uperf-bench/tasks/main.yml
- roles/uperf-bench/templates/workload.yml.j2
- tests/test_uperf.sh
- workloads/uperf-Dockerfile
Using our Redis backend we needed to sync all the uperf clients to start
up at the same time. This commit finally makes use of said backend.
> UPerf sync all clients

- docs/uperf.md
- resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
- resources/crds/ripsaw_v1alpha1_uperf_index_cr.yaml
- roles/uperf-bench/tasks/main.yml
- roles/uperf-bench/templates/server.yml.j2
- roles/uperf-bench/templates/service.yml.j2
- roles/uperf-bench/templates/workload.yml.j2
- tests/test_crs/valid_uperf.yaml
- tests/test_uperf_serviceip.sh
UPerf uses mutliple ports, which makes things a bit tricky for using K8s
services. Since with services you need to define the ports in use.
By default UPerf will use port `20000` for data plane, but then it opens
another port random(35000,4XXXX?) for control it seems. Orgionally I
was using using Jinja to create thousands of ports to open in the
service definiton, however that caused issues with the server pod.
Instead I limited the ports that were availabile for use to
20001->20041 for the control.
fixes #24
> UPerf : Pod to Service

- tests/common.sh
- tests/test_byowl.sh
- tests/test_crs/valid_byowl.yaml
- tests/test_fio.sh
- tests/test_fiod.sh
- tests/test_iperf3.sh
- tests/test_sysbench.sh
- tests/test_uperf.sh
- tests/test_uperf_serviceip.sh
This adds a `git_pod()` function to `common.sh` that is more robust than the existing `check_pods()` function. It also uses the new function to validate the ripsaw pod before allowing the test CR to be applied. All test scripts are updated to use the new function.
> Improve CI pod checking, including ripsaw itself

- tests/test_pgbench.sh
Instead of a lazy `sleep 10`, let's actually validate the output we expect from the kubectl command.
> better adjustment for potential race condition in test script

- resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
- roles/fio-distributed/templates/configmap.yml.j2
- tests/test_crs/valid_fiod.yaml
- tests/test_crs/valid_fiod_store.yaml
Corrects the CR file to work with the changes from PR #154. Also makes a slight change to the CR and the configmap so that the `filesize` scale unit is passed in the CR instead of coded into the configmap.
> correct example CR file for changes in PR #154

- docs/fio_distributed.md
- resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
- roles/fio-distributed/defaults/main.yml
- roles/fio-distributed/templates/client.yaml
- roles/fio-distributed/templates/configmap.yml.j2
- tests/test_crs/valid_fiod.yaml
- tests/test_crs/valid_fiod_store.yaml
- tests/test_fiod.sh
There are several things going on in this commit:
1. The `elasticsearch` and `test_user` keys in the CR now have default values. This means that `elasticsearch.port`, `elasticsearch.index`, and `test_user` can all be left undefined or blank, and they will default to `9200`, `ripsaw-fio`, and `ripsaw`, respectively. The `elasticsearch.server` key can be left blank or undefined, and it will default to `''`, which will fail the jinja2 test in the template and skip adding the es environment vars.
2. Environment vars in the client template are now set in a k8s-native way, and the jinja2 logic surrounding the es stuff is simplified.
3. When defining the `storagesize` in the CR, you currently need to use IEC prefixes for base-2 values (KiB, MiB, etc). To make the values for fio consistent with …
> improve fio jobfile and allow for more customization in the CR

- tests/test_byowl.sh
- tests/test_fiod.sh
- tests/test_iperf3.sh
- tests/test_pgbench.sh
- tests/test_smallfile.sh
- tests/test_sysbench.sh
- tests/test_uperf.sh
- tests/test_uperf_serviceip.sh
- tests/test_ycsb.sh
To aid in readability during CI testing I have enabled the usage of figlet in the test_*.sh scripts and installed the package on the CI systems. @dustinblack ++ for the initial setup
Resolves issue #126
> Enable figlet usage for ease of readability during CI testing

- resources/operator.yaml
Facilitating increasing of the number of CRs we can run together, currently defaulting to one, but after work to the roles to update labels for resources to include uuid, this can be increased to 2.
> Allow for number of workers to be increased

- tests/common.sh
- tests/test_byowl.sh
- tests/test_fiod.sh
- tests/test_iperf3.sh
- tests/test_pgbench.sh
- tests/test_smallfile.sh
- tests/test_sysbench.sh
- tests/test_uperf.sh
- tests/test_uperf_serviceip.sh
- tests/test_ycsb.sh
Many of the issues we see in ci is during kubectl --wait functions. I have added a wait_for function which will dump the last 40 (arbitrary number open to adjustment) lines of the benchmark-operator logs as well as any additional pods you provide to the function.
I updated the existing test_*.sh files to use wait_for however adjustment may be desired for any additional pod logs that may want to be shown.
Additionally, I added a completion timeout of 300s for byowl and sysbench since one was not set previously.
> Collect and display more detail for CI Issue #71

- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/uperf-bench/tasks/main.yml
- tests/test_uperf.sh
- watches.yaml
The built-in status from the Ansible Operator doesn't fit the different
cycles a benchmark workflow goes through. For example, our YCSB workload
has 3 phases:
- Starting
- Load
- Run
Other workloads such as smallfile have different stages of run the run
phase.
This PR only addresses UPerf, but will serve as an example going
forward.
> Mange the status of the workloads

- docs/pgbench.md
- resources/crds/ripsaw_v1alpha1_pgbench_cr.yaml
- roles/pgbench/defaults/main.yml
- roles/pgbench/tasks/generate_num_databases.yml
- roles/pgbench/tasks/main.yml
- roles/pgbench/tasks/run_workload.yml
- roles/pgbench/templates/workload.yml.j2
- tests/test_crs/valid_pgbench.yaml
based on a pattern supplied in the CR file
This allows us an outer loop that will ramp up the number of databases we are testing against based on a pattern option supplied in the CR file.
> Implement looping through a list of total number of databases

- tests/common.sh
- tests/test_byowl.sh
- tests/test_fiod.sh
- tests/test_iperf3.sh
- tests/test_pgbench.sh
- tests/test_smallfile.sh
- tests/test_sysbench.sh
- tests/test_uperf.sh
- tests/test_uperf_serviceip.sh
- tests/test_ycsb.sh
Error function gets triggered on any ERR return as well as exit code 1. It provides the logs of the benchmark operator as well as the new ansible sidecar. I removed the benchmark operator log dump from the wait_for function since it was now redundant.
> Added trap on error function

- tests/common.sh
To avoid leaving hanging resources such as statefulsets etc we can delete everything in the wait_clean function not just specific types.
> wait_clean now deletes all not just pods, jobs, etc

- roles/fio-distributed/templates/servers.yaml
- roles/iperf3-bench/templates/client.yml.j2
- roles/load-ycsb/tasks/main.yml
- roles/pgbench/templates/workload.yml.j2
- roles/smallfile-bench/templates/workload_job.yml.j2
- roles/sysbench/templates/workload.yml
- roles/ycsb-bench/tasks/main.yml
Although this will increase the time to run the CI test as it'll always pull down the latest image, it will also ensure that no one is running tests with an older version of the benchmark image.
We should be following this up with using a specific tag/version for each of the benchmark images as well, so that once we implement versioning in Ripsaw we can then accordingly have a branch in magazine/snafu with the same number.
> defaulting image pull policy to always

- test.sh
This will be used to (hopefully) pass more information back to github on completion of a CI run.
> Added results.xml to be passed on CI completion

- tests/test_crs/valid_uperf.yaml
Just to reduce the runtime as current testing time takes over 500 seconds
> reducing uperf test runtime for CI

- resources/crds/ripsaw_v1alpha1_pgbench_cr.yaml
- roles/pgbench/defaults/main.yml
- roles/pgbench/tasks/calculate_timeouts.yml
- roles/pgbench/tasks/run_workload.yml
- roles/pgbench/templates/workload.yml.j2
Note: This includes the commits for #166 and so is intended to be merged behind that one.
The changes here get rid of the user-supplied timeout in the CR and instead use a series of simple calculations to dynamically determine appropriate timeouts for the load and run phases based on the scale and loop iterations of the test.
> Pgbench timeout

- roles/pgbench/templates/workload.yml.j2
Note: This includes the commits for #166 and so is intended to be merged behind that one.
This change introduces additional timestamps for the start times of the job and of the sample. Existing timestamps record the end-time of the sample and the intermediate times for throughput/latency checks. Adding these additional timestamps to the index allows for better annotations in the visualizations, as can be seen in this sample data: 
http://marquez.perf.lab.eng.rdu2.redhat.com:3000/d/AIpX4_HZz/pgbench-dashboard?orgId=1&from=1564757895580&to=1564763492228&var-uuid=All&var-user=All
> Pgbench timestamps

- roles/uperf-bench/templates/service.yml.j2
Now that the operator has its own svcip I noticed that we had a bug. We
are missing the labels totally for the svcip. This is to fix that.
> ServiceIP bug

- run_test.sh
- test.sh
- tests/common.sh
To avoid having to re-run the entire test bed for a single (possibly transient failure) we re-run a failed test once.
Additionally, this adds the following changes to the CI scripts:
- Added a "Retries" column in the github markdown output
- Broke the test.sh script into two, adding run_test.sh
- run_test.sh takes a parameter (the test) to be run and cycles through the test until pass or X (now 1) retries are met
- Added operator_requirements to apply_operator to ensure everything is there before we run
- Test output is predominately suppressed unless we fail, at which point it is printed to the CI console.
- Added the max_concurrent (currently 1) variable which can be used if we decide to run tests in parallel in the future.
> Tests are now retried once upon failure

- test.sh
Calculate and display the duration of each CI test in the markdown comment pushed to github
> Added duration of test to markdown

- roles/fio-distributed/templates/client.yaml
This change is needed because snafu is using invalid syntax for python
directory/file names
> changed dash to underscore for fio wrapper

- test.sh
To fix the mashed together output from the use of xargs I've swapped to parallel which keeps the output for each test together.
> Replace xargs with parallel

- roles/smallfile-bench/templates/workload_job.yml.j2
smallfile_cli.py is in /usr/local/bin, when run with python the PATH variable doesn't include /usr/local/bin which causes the job to fail. Invoke the
cli directly instead.
Fixes: https://github.com/cloud-bulldozer/ripsaw/issues/230
Signed-off-by: Vasu Kulkarni <vasu@redhat.com>
> smallfile_cli.py is in /usr/local/bin, run the script directly

- docs/uperf.md
- resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
- roles/uperf-bench/templates/server.yml.j2
- roles/uperf-bench/templates/workload.yml.j2
- tests/test_crs/valid_uperf.yaml
- tests/test_crs/valid_uperf_serviceip.yaml
Adding Multus Support for macvlan tested.
User must create port per pod, multi-pod not supported.
> Multus support

- resources/crds/ripsaw_v1alpha1_smallfile_cr.yaml
- roles/smallfile-bench/templates/workload_job.yml.j2
- tests/test_crs/valid_smallfile.yaml
Do not merge or test before snafu PR 50 is merged!
Using this branch I ran a 3-sample multi-operation smallfile test in AWS Ceph cluster.
take out loop for different operations
make operation list a CSV list for run_snafu.py smallfile_wrapper
no smallfile-master dir anymore
> switch smallfile to using run_snafu.py

- README.md
- docs/metadata.md
- playbook.yml
- roles/backpack/tasks/main.yml
- roles/backpack/templates/backpack.yml
- tests/test_backpack.sh
- tests/test_crs/valid_backpack.yaml
- tests/test_list
Adding backpack/stockpile to ripsaw operator image. 
If the following are set in the workload yaml it will execute the backpack daemonset to be created.
```
...
spec:
es_server: "my.elastic.server.foo"
es_port: 9200
metadata_collection: true
workload: ...
```
Additional options can be defined for privledged pods as well as passing a kubeconfig to the image for added data collection per https://github.com/dry923/ripsaw/blob/backpack/docs/metadata.md.
> Adding backpack/stockpile to Ripsaw

- README.md
- playbook.yml
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/backpack/tasks/main.yml
- roles/backpack/templates/backpack.yml
- tests/common.sh
- tests/test_backpack.sh
- tests/test_byowl.sh
- tests/test_crs/valid_byowl.yaml
- tests/test_crs/valid_fiod.yaml
- tests/test_crs/valid_fs_drift.yaml
- tests/test_crs/valid_hammerdb.yaml
- tests/test_crs/valid_iperf3.yaml
- tests/test_crs/valid_pgbench.yaml
- tests/test_crs/valid_smallfile.yaml
- tests/test_crs/valid_sysbench.yaml
- tests/test_crs/valid_uperf.yaml
- tests/test_crs/valid_ycsb-mongo.yaml
- tests/test_fiod.sh
- tests/test_fs_drift.sh
- tests/test_hammerdb.sh
- tests/test_iperf3.sh
- tests/test_pgbench.sh
- tests/test_smallfile.sh
- tests/test_sysbench.sh
- tests/test_uperf.sh
- tests/test_uperf_serviceip.sh
- tests/test_ycsb.sh
- watches.yaml
**Updated 11/7**
Adding:
- Metadata State to benchmark
- Reduced reconciliation time to 3s
- We now only ever set the cr_state once in playbook.yml
- Added wait_for_backpack function to ci tests
- Resolved issue with backpack daemonset not allowing other pods to run
> Adding metadata_complete flag to ripsaw crd

- roles/byowl/templates/workload.yml
- roles/hammerdb/templates/db_creation.yml
- roles/hammerdb/templates/db_workload.yml
- roles/iperf3-bench/templates/client_store.yml.j2
- roles/iperf3-bench/templates/server.yml.j2
- roles/pgbench/templates/workload.yml.j2
- roles/uperf-bench/templates/server.yml.j2
- roles/uperf-bench/templates/workload.yml.j2
- tests/test_crs/valid_fiod.yaml
To help avoid issues with using old images I have added imagePullPolicy: Always to the remaining benchmarks that did not have them.
> Adding imagePullPolicy: Always to all benchmarks

- resources/crds/ripsaw_v1alpha1_fs_drift_cr.yaml
- resources/crds/ripsaw_v1alpha1_smallfile_cr.yaml
- roles/fs-drift/templates/workload_job.yml.j2
- roles/smallfile-bench/templates/workload_job.yml.j2
- tests/test_crs/valid_fs_drift.yaml
- tests/test_crs/valid_smallfile.yaml
This makes the 2 CRs conform to the snafu README.md documentation for how to point to elastic search.
> so run_snafu.py can work in CI

- tests/test_crs/valid_smallfile.yaml
must be longer than 1 second to insert into ripsaw-smallfile-rsptimes index
This fixes a problem noticed in [snafu PR 99](https://github.com/cloud-bulldozer/snafu/pull/99#issuecomment-563419259).
Please mark OK TO TEST and merge ASAP.
> lengthen test to generate response time data to ES

- roles/uperf-bench/templates/service.yml.j2
Uperf service targeted benchmark is missing pod selector, this PR includes one based on the pod's type label.
> Add service selector to uperf svc jobs

- roles/smallfile-bench/tasks/main.yml
- roles/smallfile-bench/templates/workload_job.yml.j2
Required to fix https://github.com/cloud-bulldozer/snafu/issues/98
These variables are required to the smallfile snafu wrapper, so that this will be able to synchronize smallfile status using redis channel subscriptions
> Pass number of clients and redis host to smallfile jobs

- run_test.sh
- tests/common.sh
The namespace was not getting cleaned up during ci tests. This would sometimes lead to things being stuck in pending states. This will now delete the namespace in wait_clean and also ensure its created in the operator_requirements.
> Adding namespace deletion/creation to requirements

- deploy/20_role.yaml
- deploy/50_pod_security_policy.yml
- roles/fio-distributed/templates/servers.yaml
- roles/fs-drift/templates/workload_job.yml.j2
- roles/smallfile-bench/templates/workload_job.yml.j2
- tests/common.sh
- tests/test_crs/valid_fiod_hostpath.yaml
- tests/test_crs/valid_fs_drift_hostpath.yaml
- tests/test_crs/valid_smallfile_hostpath.yaml
- tests/test_fiod.sh
- tests/test_fs_drift.sh
- tests/test_smallfile.sh
Doing I/O benchmarks directly on top of containers implies making those I/O operations on the container filesystem, usually OverlayFS. This PR enables some ripsaw benchmarks to perform those tests on hostPaths  devices in order to avoid the OverlayFS layer.
Accessing to hostPath volumes require running pod as privileged, so the role has been also granted usage to the hostaccess SCC
> Enable I/O tests to benchmark hostPath volumes

- tests/test_ycsb.sh
StatefulSet no longer tolerates the apps/v1beta1 API group.   It has been v1 since 1.9, so this change should be safe.
> Support StatefulSet v1 spec in test_ycsb.sh wrapper

- tests/common.sh
The wait_for_backpack function would sometimes timeout due to the amount of time it would take to pull down the image. Particularly when run on multiple node clusters.
> Increasing the time to wait for backpack to complete

- tests/common.sh
There are times that we run a wait_clean after a wait_clean. When the namespace is already deleted this can throw an error. This adds a check for the existence of the namespace first.
> Adding a check to the namespace deletion

- tests/test_fiod.sh
- tests/test_fs_drift.sh
- tests/test_smallfile.sh
Snafu ci expects there to be a trap finish function that it can remove to allow the existing pods to run longer so it can get the uuid from them.
> Changing trap wait_clean to trap finish to fix snafu ci error

- tests/common.sh
Previously if backpack failed to launch during a ci test it would continue anyway. This will now have it fail and exit properly.
> Backpack will now properly fail the ci test if it does not launch

- roles/fs-drift/templates/workload_job.yml.j2
- roles/smallfile-bench/templates/workload_job.yml.j2
Ensure IO clients spread among different nodes
> Add pod anti-affinity rules to IO jobs

- docs/uperf.md
- roles/uperf-bench/templates/server.yml.j2
- roles/uperf-bench/templates/workload.yml.j2
- tests/test_crs/valid_uperf_resources.yaml
- tests/test_uperf.sh
In order to use CPU manager capabilities at uperf containers we should be able to configure compute resources to get a guaranteed QoS on pods.
> Configure uperf compute resources

- test.sh
In the test.sh script we were previously updating the operator image straight away. When we would later run git diff on the files this would always result in resources/operator.yml always getting flagged as changed. This moves the ordering to after the git diff line
> Reordering updating of image

- tests/test_crs/valid_fs_drift.yaml
original duration was 5 seconds, but
fs-drift default report interval[ changed from 1 to 5 sec](https://github.com/parallel-fs-utils/fs-drift/commit/86150806bc426d4675a43f55c9d42bcc011b1cfe),
so no records were getting generated for thread counters
causing CI test to fail when it looked for records in
corresponding index.
> lengthen the fs-drift CI test to 15

- roles/fio-distributed/templates/configmap.yml.j2
for the latest version of fio (3.19), unit_base in job file doesnt
support string
> fix fiojob for fio-3.19

- tests/common.sh
There is a case where we may error out during one of the log messages below which will cause us to re-error. Moving the ERRORED state change above and adding an if statement should resolve this.
> Fixing potential infinite loop when logging errors

- roles/uperf-bench/templates/configmap.yml.j2
- tests/test_crs/valid_uperf.yaml
Bidirectional test needs several groups to run write and read workloads in parallel. The code included in this PR opens and closes a new uperf group per workload.
> Fix bidirectional test

- docs/fio_distributed.md
- roles/fio-distributed/templates/client.yaml
- roles/fio-distributed/templates/configmap.yml.j2
- tests/test_crs/valid_fiod.yaml
Added logic to fio-distributed to pre-fill the cluster before running the user provided test. 
This PR un-blocks the perf-sclae team with testing OCS.
@aakarshg @bengland2 @jtaleric @dry923 @dustinblack
> Add block to pre-fill cluster if fiod.prefill is true

- docs/installation.md
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- tests/test_hammerdb.sh
- tests/test_pgbench.sh
- tests/test_ycsb.sh
Updating the CRD api to v1. This will require changes to the crd file as well as changes to cr's using older api versions for kinds deployment and stateful sets.
Additional changes may need to be made on a benchmark to benchmark basis to account for the tighter restrictions around cr validation.
> Updating CRD api to version v1

- run_test.sh
Adding a small (<10 second) random sleep to the start of each workload CI test. This is to help avoid potential command collision. 
This also may resolve https://github.com/cloud-bulldozer/ripsaw/issues/319
> Adding a short sleep to each CI test run to avoid command collision

- .gitignore
- README.md
- roles/backpack/templates/backpack.yml
- roles/byowl/templates/workload.yml
- roles/fio-distributed/templates/client.yaml
- roles/fio-distributed/templates/servers.yaml
- roles/fs-drift/templates/workload_job.yml.j2
- roles/hammerdb/templates/db_creation.yml
- roles/hammerdb/templates/db_workload.yml.j2
- roles/iperf3-bench/templates/client.yml.j2
- roles/iperf3-bench/templates/server.yml.j2
- roles/pgbench/templates/workload.yml.j2
- roles/smallfile-bench/templates/workload_job.yml.j2
- roles/sysbench/templates/workload.yml
- roles/uperf-bench/templates/server.yml.j2
- roles/uperf-bench/templates/workload.yml.j2
This adds an optional workload argument image which takes the image location. This is to make debugging and testing changes easier by allowing you to pass a different image location without having to rebuild the operator image.
> Adding optional image location for workloads

- roles/backpack/templates/backpack.yml
During a PR 315 the spacing for securityContext got messed up. This resolves it.
> Fixing incorrect indentation in backpack template

- README.md
- docs/cerberus.md
- playbook.yml
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/cerberus/tasks/main.yml
This allows the user to pass a cerberus_url variable to ripsaw via the CR file. If provided it will set the benchmark status of Cerberus to connected. If Cerberus reports a failure during the lifecycle of the workload the benchamrk status will be set to Error and it will not proceed further. It will NOT kill any running pods or make any modifications to the cluster. It will just halt any further progress. 
Additionally, once an error state has been reached it will not be reset by ripsaw. The workload will need to either be restarted or you will need to set the state back to its previous value by hand.
Cerberus: https://github.com/openshift-scale/cerberus
> Adding Cerberus integration

- resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
- roles/fio-distributed/templates/client.yaml
- roles/fio-distributed/templates/configmap.yml.j2
- tests/test_crs/valid_fiod.yaml
- tests/test_crs/valid_fiod_hostpath.yaml
This has been tested with a 112-OSD Ceph cluster.   It allows for really quick tests to debug workload parameters, etc.  by making  the 300-second prefill sleep configurable (default 0).   But it can handle really long tests efficiently by leveraging Alex's prefill functionality to do the full file write only once with maximum I/O size, and then the actual write test is done on a time-limited basis.   Some fixes were needed to support each test type independently.   We need this for OCS QE.
> Fio yaml enhancements

- tests/test_crs/valid_fiod.yaml
- tests/test_crs/valid_fiod_hostpath.yaml
cut down on number of I/O sizes and numjobs values for valid_fiod
cut down on samples and number of I/O sizes for valid_fiod_hostpath
tested with minikube - I was able to reproduce the timeout before this fix.  With this fix I tested it twice and no timeout occurred.
> shorten both of these tests up so CI doesn't timeout

- resources/backpack_role.yaml
- tests/check_es.py
- tests/common.sh
- tests/test_backpack.sh
- tests/test_byowl.sh
- tests/test_crs/valid_backpack.yaml
- tests/test_fiod.sh
- tests/test_fs_drift.sh
- tests/test_hammerdb.sh
- tests/test_iperf3.sh
- tests/test_pgbench.sh
- tests/test_smallfile.sh
- tests/test_sysbench.sh
- tests/test_uperf.sh
- tests/test_ycsb.sh
Added check_es python script that will check an ES instance for a given uuid and index. This is used to help validate that the tests ran and indexed properly. This was only added to workloads that utilize snafu.
Additionally, updated the backpack CI test to run as a privileged container with a service account. This way we can ensure we check as many of the functions of the pod as possible. However, I did have to add in a sleep after the workload was complete as ES seemed to take some time to process the data and make it available to check via the check_es script.
> Adding logic to CI testing to check ES for workload results

- docs/metadata.md
- roles/backpack/templates/backpack.yml
This will allow the daemonset to be targeted on nodes that contain a specific label name=value.
You can now add a list of labels in name/value pairs like below. This is an implicit OR so the node will have to match any of the labels provided.
```
metadata:
collection: true
targeted: false
label:
- [ 'foo', 'bar' ]
- [ 'awesome', 'sauce' ]
```
> Adding optional label parameters to metadata daemonset. 

- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
This fixes a schema error that shows when you try and run ```oc explain```
> Fixing CRD schema error

- README.md
Pointing to old channel in README.md
> Fix Channel

- docs/ycsb.md
- roles/load-ycsb/tasks/main.yml
- roles/load-ycsb/templates/workload.yml.j2
- roles/ycsb-bench/tasks/main.yml
- roles/ycsb-bench/templates/workload.yml.j2
This commit will facilitate pinning of the workload/load pods
to a specific nodes, and also in the process moves the pod/job
definition into ansible templates
> allow for pinning of ycsb load/workload pods

- tests/common.sh
This would cause a CI failure previously if the oc command was installed but securitycontextconstraints.security.openshift.io did not exist. This is the case in minikube if the user also installed oc.
> Adding additional check for scc in CI testing

- tests/common.sh
Some directories were renamed in a recent PR and the if statements in common.sh were not updated. This resolves the issue.
> Fixing if statement for renamed directories

- build/Dockerfile
- image_resources/centos8-appstream.repo
- playbook.yml
- requirements.yml
- roles/backpack/tasks/main.yml
- roles/byowl/tasks/main.yml
- roles/cerberus/tasks/main.yml
- roles/fio_distributed/tasks/main.yml
- roles/fs-drift/tasks/main.yml
- roles/iperf3/tasks/main.yml
- roles/pgbench/tasks/check_clients.yml
- roles/pgbench/tasks/init.yml
- roles/pgbench/tasks/main.yml
- roles/pgbench/tasks/prep_workload.yml
- roles/pgbench/tasks/run_workload.yml
- roles/smallfile/tasks/main.yml
- roles/sysbench/tasks/main.yml
- roles/sysbench/templates/sysbench.sh.j2
- roles/uperf/tasks/main.yml
- roles/ycsb/tasks/main.yml
This new version is based in ubi8 and uses python-3.6 and ansible-2.9.6
k8s_status module is no longer available and has been renamed to  operator_sdk.util.k8s_status since now is provided by an Ansible collection.
> migrate  to ansible-operator:v0.17.0

- roles/backpack/templates/backpack.yml
- tests/test_backpack.sh
Improve backpack readiness probe to check for `/tmp/indexed` which is created after a successful execution of stockpile-wrapper
> Backpack readiness probe

- tests/check_es.py
- tests/common.sh
- tests/test_backpack.sh
- tests/test_byowl.sh
- tests/test_fiod.sh
- tests/test_fs_drift.sh
- tests/test_hammerdb.sh
- tests/test_iperf3.sh
- tests/test_pgbench.sh
- tests/test_smallfile.sh
- tests/test_sysbench.sh
- tests/test_uperf.sh
- tests/test_uperf_serviceip.sh
- tests/test_ycsb.sh
There are situations where check_es.py script is not able to find documents on ES. This PR updates that script to refresh the index prior to query it.
In addition, it also standardizes some of the CI code and simplifies the wait_clean function.
> Refresh ES index before checking for documents

- build/Dockerfile
- image_resources/centos8-appstream.repo
- meta/main.yml
- playbook.yml
Update Operator framework from 0.17.0 to 0.17.1
I initially did this from 0.8.1 to 0.17.1 but @rsevilla87 was quicker to push this to master :laughing: 
This is now based on ubi8 - thus we need the CentOS AppStream to install redis
https://github.com/operator-framework/operator-sdk/issues/2648
> SDK update

- README.md
YCSB and pgbench have reconciliation enabled. Updating the docs accordingly. Thanks for pointing this out @dustinblack
> Fix documention about reconciliation loop

- roles/uperf/templates/service.yml.j2
20012 will not be included and will match
https://github.com/cloud-bulldozer/ripsaw/blob/57142bbc053970f2513c19480a8a741f2e13f5f2/roles/uperf/templates/server.yml.j2#L36
with this we can avoid uperf errors
```
** TCP: Cannot connect to 172.30.225.73:20011 No route to host
WARNING: Errors detected during run
```
> service port should match with open server ports

- roles/uperf/templates/workload.yml.j2
This keeps uperf server/client pairs on separate hosts if possible.This fixes issue 363.
> Updated the antiaffinity rule to keep server/client pairs separate

- build/Dockerfile
- image_resources/centos8-appstream.repo
Fixes broken RPM urls like:
STEP 5: RUN rpm --nodeps -i http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/centos-repos-8.1-1.1911.0.9.el8.x86_64.rpm http://mirror.centos.org/centos/8-stream/BaseOS/x86_64/os/Packages/centos-gpg-keys-8.1-1.1911.0.7.el8.noarch.rpm
curl: (22) The requested URL returned error: 404 Not Found
> Fix broken URLs

- roles/uperf/templates/service.yml.j2
Uperf pod to service workload doesn't work as expected due to how uperf works itself.
When an uperf server initializes a benchmark, it allocates a series of ephemeral ports that are be used for running the workload.
The issue arises when running more than one replica these of uperf slave pods behind a load balancer (a k8s service in this case), since the ephemeral port(s) are allocated only in one of the pods (The pod who received the handshake over the control port 20000), this means that subsequent transactions can fail since they could be steered to a different pod which is not listening in expected the ephemeral port.
That would explain error traces like the below:
```console
** TCP: Cannot connect to 172.30.161.246:20003 Connection refused
** TCP: Cannot connect to …
```
> Select only one pod in uperf service

- README.md
- docs/fio_distributed.md
- resources/crds/ripsaw_v1alpha1_fio_distributed_vm_cr.yaml
- roles/fio_distributed/defaults/main.yml
- roles/fio_distributed/tasks/main.yml
- roles/fio_distributed/templates/client.yaml
- roles/fio_distributed/templates/server_vm.yml.j2
Adds kubevirt option to fio-distributed workload.
This spawns kubevirt VMs where the fio server is run in.
Please first merge https://github.com/cloud-bulldozer/ripsaw/pull/353 before merging this
--> I will rebase after this is done
@bengland2 @jeniferh
> Fio in vms

- README.md
- docs/vegeta.md
- resources/crds/ripsaw_v1alpha1_vegeta_cr.yaml
- roles/vegeta/tasks/main.yml
- roles/vegeta/templates/targets.yml.j2
- roles/vegeta/templates/vegeta.yml.j2
- tests/common.sh
- tests/test_crs/valid_vegeta.yaml
- tests/test_crs/valid_vegeta_hostnetwork.yaml
- tests/test_list
- tests/test_vegeta.sh
Adding vegeta benchmark. It accepts CRDs like the following:
```yaml 
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
name: vegeta-benchmark
namespace: my-ripsaw
spec:
elasticsearch:              <-- Optional
server: <es_instance>
port: 9200
index_name: ripsaw-vegeta
workload:
name: vegeta
args:
hostnetwork: true                     <-- Optional. Defaults to false
image: quay.io/rsevilla/vegeta:latest           <-- Optional. Defaults to quay.io/cloud-bulldozer/vegeta:latest
clients: 2  <-- Optional. Defaults to 1
targets:
- name: 100w-ka
urls:
- GET https://mydomain.com/test.png
- GET http://myunsecuredomain.com
samples: 2   <-- Optional. Defaults to 1
workers: 100              <- Optonal. Defaults to 1
duration: 10
keepalive: true           <-- Optional. Defaults …
```
> Add vegeta benchmark

- test.sh
- tests/test_pgbench.sh
- tests/test_ycsb.sh
With the new CI environment there is the chance that different runs will delete the crd while its in use by another. This change adjusts the crd name to be unique for each run.
> Updating CI test script to create unique crd names for each run

- docs/fio_distributed.md
- resources/crds/ripsaw_v1alpha1_fio_distributed_vm_cr.yaml
- roles/fio_distributed/tasks/main.yml
This enables us to define the accessMode and volumeMode of the PVC
We want this for VM workloads to schedule RWX Block PVCs
Ping @rsevilla87 @jeniferh
> Add further PVC options to the fio workload

- tests/test_backpack.sh
- tests/test_crs/valid_backpack_daemonset.yaml
- tests/test_crs/valid_backpack_init.yaml
We currently do not verify all the indexes gathered by the backpack init containers. This adds an additional test to the backpack CI script to verify them.
> Adding additional CI test for backpack init containers

- resources/backpack_role.yaml
- templates/metadata.yml.j2
Grant usage of privileged scc to the backpack-view role.
Signed-off-by: Raul Sevilla <rsevilla@redhat.com>'
> Fix privileged initContainers

- resources/backpack_role.yaml
- roles/backpack/templates/backpack.yml
- test.sh
- tests/common.sh
- tests/test_backpack.sh
Prevent backpack from trying to collect metadata not related with OCP or k8s.
Also moving the call to backpack_requirements to test_backpack to fix CI issues.
> Collect only ocp and k8s related metadata

- roles/ycsb/templates/ycsb_load.yaml
- roles/ycsb/templates/ycsb_run.yaml
The index for ycsb was defaulted to fio instead of ycsb
> Fixing wrong default index name for ycsb

- README.md
- docs/fio_distributed.md
- docs/uperf.md
- roles/fio_distributed/templates/client.yaml
- roles/fio_distributed/templates/servers.yaml
- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/workload.yml.j2
In order to enable Kata support we need to add `runtimeClassName` to the
podSpec. The user must supply the `runtime_class` to reflect the
`runtimeClassName` to use.
> Enable Kata

- resources/operator.yaml
Currently the benchmark operator will land on any available worker node. This is fine in many cases however to avoid having it being impacted by ongoing tests we should try to pin it to the workload node if possible.
> Have the benchmark operator prefer to run on a workload node

- README.md
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/uuid/tasks/main.yml
A user can now, optionally, provide a custom UUID in the CR file such as:
```
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
name: example-benchmark
namespace: my-ripsaw
spec:
uuid: 6060004a-7515-424e-93bb-c49844600dde     <------custom UUID
elasticsearch:
server: "my-es.foo.bar"
port: 9200
metadata_collection: true
cleanup: false
workload:
name: "foo"
args:
image: my.location/foo:latest
```
> Allow for a user provided UUID

- docs/fio_distributed.md
- roles/fio_distributed/templates/configmap.yml.j2
In order to produce a non-uniform distribution test with fio, this PR attempts to add the use of fio's bsrange parameter. Essentially in this PR we check whether the user is using bs or bsrange, and then loops through the test as previous.
```
if bs in args.bs
for bs in ags.bs
do test
elif bsrange in args.bsrange
for bsrange in ags.bsrange
do test
```
> Added handling of fio bsrange parameter

- README.md
- docs/scale_openshift.md
- resources/scale_role.yaml
- roles/scale_openshift/tasks/main.yml
- roles/scale_openshift/templates/scale.yml
- test.sh
- tests/common.sh
- tests/test_crs/valid_scale_down.yaml
- tests/test_crs/valid_scale_up.yaml
- tests/test_list
- tests/test_scale_openshift.sh
This will enable the ability of ripsaw to scale a cluster utilizing the snafu scale_openshift wrapper. I added the scaling to be run prior to the normal testing to make sure it doesn't impact the other ci tests as they normally run in parallel. 
Note: this requires https://github.com/cloud-bulldozer/benchmark-wrapper/pull/205
> Enabling Scaling the Cluster

- roles/scale_openshift/tasks/main.yml
Previously the scale benchmark was getting set to complete too soon. This resolves the issue
> Fixing completion check for scale_openshift

- roles/iperf3/templates/client.yml.j2
- roles/iperf3/templates/client_store.yml.j2
- roles/iperf3/templates/server.yml.j2
- tests/test_crs/valid_iperf3.yaml
- tests/test_iperf3.sh
iperf blows up if we use hostnetwork as mentioned at https://github.com/cloud-bulldozer/benchmark-operator/issues/413. This PR fixes it and also adds a test case for iperf3 w/ hostnetwork: true
> Fix iperf3 hostnetwork and add test to it

- docs/uperf.md
Re: https://github.com/cloud-bulldozer/benchmark-operator/issues/415
This is to help explain that if Kata containers are not in use the runtime_class options should be removed.
> Updating uperf doc for additional details on runtime_class parameter

- templates/metadata.yml.j2
- test.sh
stockpile-wrapper must be executed in a shell to parse environment variables.
It fixes the issue of my_node_name and my_node_name not being replaced in indexed documents.
```
{
"_index": "meminfo-metadata",
"_type": "_doc",
"_id": "hjH613QBdEyVZF0pYiCX",
"_score": 1,
"_source": {
"uuid": "980c93cd-51d2-5852-a9ab-675fa8aacb4f",
"timestamp": 1601351338,
"node_name": "${my_node_name}",
"pod_name": "${my_pod_name}"
```
> Fix node name and pod name variables

- docs/kube-burner.md
- resources/crds/ripsaw_v1alpha1_kube-burner_cr.yaml
- roles/kube-burner/files/metrics-aggregated.yaml
- roles/kube-burner/files/metrics.yaml
- roles/kube-burner/tasks/main.yml
- roles/kube-burner/templates/kube-burner.yml.j2
- tests/test_crs/valid_kube-burner.yaml
- tests/test_kubeburner.sh
Configurable step size for prometheus, useful for long benchmarks since it reduces the number of indexed metrics in exchange of granularity.
Also adding selection of kube-burner metrics profile and added a new metrics profile useful for large clusters (Detailed in doc from this PR). Dashboards for both metric profiles at https://github.com/rsevilla87/kube-burner-workloads/tree/master/dashboards
> Configurable step size and metrics profile

- docs/kube-burner.md
- roles/kube-burner/files/build.yml
- roles/kube-burner/files/buildconfig.yml
- roles/kube-burner/templates/cluster-density.yml.j2
Make builds from the cluster-density workload lighter by changing the build strategy to dockerStrategy and using the image registry.fedoraproject.org/fedora-minimal for that.
buildconfigs still use the original sourceStrategy, so with this change we'll test both sourceStrategy and dockerStrategy for OCP builds.
Builds based on dockerStrategy last ~ 30 seconds and the original ones > 1 minute.
```
[root@ip-172-31-78-162 ~]# oc get build
NAME                                                       TYPE     FROM          STATUS     STARTED              DURATION
cluster-density-1-7a01f8c5-88ef-5e82-b5d7-3a08f9b501a0     Docker   Dockerfile    Complete   About a minute ago   31s
cluster-density-5-7a01f8c5-88ef-5e82-b5d7-3a08f9b501a0     Docker   Dockerfile    Complete   About a minute ago   31s …
```
> Lighter builds for cluster-density

- roles/uperf/templates/configmap_script.yml.j2
- roles/uperf/templates/server_vm.yml.j2
- roles/uperf/templates/workload_vm.yml.j2
Fix uperf test in virtualized environments. Use uperf from the official Fedora repositories instead the pbench ones.
Fixes: https://github.com/cloud-bulldozer/benchmark-operator/pull/431
> Fix uperf in VMs

- docs/fio_distributed.md
- roles/fio_distributed/templates/client.yaml
This commit adds the ability to send fio results to the client pod
logs. This was bought up in
https://github.com/cloud-bulldozer/benchmark-operator/issues/417
If workload_args include
fio_json_to_log: true
all the fio-result.json files found in /tmp/fiod-$uuid will
be sent to the log.
> Option to send fio results to client pod log

- docs/kube-burner.md
- roles/kube-burner/templates/cluster-density.yml.j2
- roles/kube-burner/templates/kubelet-density-heavy.yml.j2
- roles/kube-burner/templates/kubelet-density.yml.j2
If login is required for the ES server when pushing prometheus data. It can be supplied in the workload.args section of the yaml as prom_es_user and prom_es_pass.
> Allow passing workload.args.prom_es_user and prom_es_pass

- docs/prometheus.md
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/fio_distributed/templates/client.yaml
- roles/fs-drift/templates/workload_job.yml.j2
- roles/hammerdb/templates/db_mssql_workload.yml.j2
- roles/hammerdb/templates/db_mysql_workload.yml.j2
- roles/hammerdb/templates/db_postgres_workload.yml.j2
- roles/kube-burner/templates/cluster-density.yml.j2
- roles/kube-burner/templates/kubelet-density-heavy.yml.j2
- roles/kube-burner/templates/kubelet-density.yml.j2
- roles/pgbench/templates/workload.yml.j2
- roles/scale_openshift/templates/scale.yml
- roles/smallfile/templates/workload_job.yml.j2
- roles/stressng/templates/stressng_workload.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/vegeta/templates/vegeta.yml.j2
- roles/ycsb/templates/ycsb_load.yaml
- roles/ycsb/templates/ycsb_run.yaml
- tests/test_crs/valid_kube-burner.yaml
Per our previous discussions this PR renames the prometheus.server|port|parallel to add es_server|port|parallel. This aims to reduce some confusion from the end user.
NOTE: this does not change the environment variable passed to benchmark-wrapper
> Rename the prometheus ES server|port|parallel to es_server|port|parallel

- docs/kube-burner.md
- resources/crds/ripsaw_v1alpha1_kube-burner_cr.yaml
Fixing doc and kube-burner cr for updated prometheus.es_server. These were missed w/ the last PR
> Fixing doc and kube-burner cr for updated prometheus.es_server

- roles/kube-burner/files/metrics-aggregated.yaml
- roles/kube-burner/files/metrics.yaml
- roles/kube-burner/tasks/main.yml
Several changes in kube-burner metrics:
- kubelet-density and kubelet-density-heavy didn't allow selecting metric profile
- Add services count
- Add etcd is leader
- Replace top10 by top3 to cut down number of indexed documents
> container_memory_rss instead memory_usage.

- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- tests/test_backpack.sh
Global_overrides was not present in the Benchmark CRD, so the parameters from this option vanish when creating the benchmark.
On the other hand, this is a quick fix for this. As a long term fix we should nest job_params, global_overrides among others under workload.
> Fix global overrides

- docs/kube-burner.md
- roles/kube-burner/templates/cluster-density.yml.j2
- roles/kube-burner/templates/kubelet-density-heavy.yml.j2
- roles/kube-burner/templates/kubelet-density.yml.j2
We can use the same notation as the python library.
Changes in kube-burner at: https://github.com/cloud-bulldozer/kube-burner/pull/27
> Remove authentication ES parameters from kube-burner

- roles/uperf/tasks/main.yml
During uperf run using OpenShift Virtualization, typo found which prevents changing the client state to "Clients Running" in the operator.
> Typo in uperf tasks for VM run

- docs/kube-burner.md
- roles/kube-burner/files/configmap.yml
- roles/kube-burner/files/deployment.yml
- roles/kube-burner/tasks/main.yml
- roles/kube-burner/templates/cluster-density.yml.j2
It is common in production deployments for pods in deployments to use
ConfigMaps. We should try to replicate that.
> Add ConfigMaps to cluster-density kube-burner tests

- docs/byowl.md
- roles/byowl/templates/workload.yml
Changes:
* Fixes issue with nodeSelectors not being able to take in hyphenated labels (i.e. node-role.kubernetes.io/master) due to jinja2 forcing yaml keys to not have hyphens.
* Adds tolerations to workload_args which can take in a list of tolerations
> Byowl Taint and Toleration

- docs/stressng.md
- resources/crds/ripsaw_v1alpha1_stressng_cr.yaml
- roles/stressng/templates/stressng_workload.yml.j2
Intendation for the nodeselector field in the stressng job template contained a hard tab, have updated to soft spaces like the rest of the template so the node selector is in the right level within the pod spec. Also converting the field to JSON to allow passing in a map of node selector key/value pairs similar to the vegeta workload.
> Update node selector in stressng job spec

- roles/sysbench/templates/workload.yml
Adds a writeable emptyDir volume to use as working directory for sysbench so that fileio tests can complete.
Currently fileio tests fail as the container working directory is read only:
```bash
sysbench 1.0.17 (using system LuaJIT 2.1.0-beta3)
Running the test with following options:
Number of threads: 1
Initializing random number generator from current time
Extra file open flags: (none)
128 files, 16MiB each
2GiB total file size
Block size 16KiB
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing sequential write (creation) test
FATAL: Cannot create file 'test_file.0' errno = 9 (Bad file descriptor)
````
After the change the fileio test completes:
```bash
sysbench 1.0.17 (using system LuaJIT 2.1.0-beta3) …
```
> Set writeable working directory for sysbench tests

- docs/fio_distributed.md
- roles/fio_distributed/templates/servers.yaml
Changes:
* Fio workloads will be able to add generic node selectors as well as generic tolerations
* The `pin_server` arg will be removed, but the feature is still available by using the `nodeselector` with the `kubernetes.io/hostname` label
> adding fio nodeselector and tolerations with docs

- roles/kube-burner/files/metrics-aggregated.yaml
- roles/kube-burner/files/metrics.yaml
- roles/kube-burner/templates/cluster-density.yml.j2
- roles/kube-burner/templates/kubelet-density-heavy.yml.j2
- roles/kube-burner/templates/kubelet-density.yml.j2
Remove conntrack metrics, and get per container CPU and memory metrics on master nodes.
Conntrack metrics are not useful in final reporting (this metric is more meaningful in real time as presented in the ocp performance-dashboard)
Per container CPU and memory metrics is useful to have more granularity and also improve benchmark-comparison.
> Remove conntrack metrics

- docs/uperf.md
- roles/iperf3/templates/client.yml.j2
- roles/iperf3/templates/client_store.yml.j2
- roles/iperf3/templates/server.yml.j2
- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/vegeta/templates/vegeta.yml.j2
- tests/test_crs/valid_uperf_resources.yaml
- tests/test_uperf.sh
The title says it all.
The benchmark-operator and backpack (this one is used in case of privileged metadata collection) SAs are already bound to the privileged SCC, so no further actions are required.
> Fix uperf hostNetwork and add test case for it

- roles/uperf/templates/workload.yml.j2
adds run_id to uperf workloads as an option
depends on https://github.com/cloud-bulldozer/benchmark-wrapper/pull/229
> adding run_id to uperf

- docs/kube-burner.md
- resources/crds/ripsaw_v1alpha1_kube-burner_cr.yaml
- roles/kube-burner/tasks/main.yml
- roles/kube-burner/templates/kube-burner.yml.j2
This PR enables kube-burner for remote config/metrics-profile retrieval.
> Remote configuration retrieval for kube-burner

- roles/uperf/templates/workload_vm.yml.j2
@jeniferh found uperf VM workload had same host pinned as server.
Thank you for finding this! 😃
> Fix pinned server in uperf workload vm template. Courtesy of @jeniferh.

- roles/kube-burner/templates/cluster-density.yml.j2
Was fixed by https://github.com/cloud-bulldozer/benchmark-operator/pull/478, we don't need this change anymore
> Revert "add image var in imagestream.yml"

- docs/elastic.md
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/uperf/templates/configmap_script.yml.j2
Add option to disable certificate verification when connecting to Elasticsearch.
This functionality was already supported by benchmark-wrapper.
Using for ES clusters with self-signed certs.
> Support elasticsearch.verify_cert for benchmark-wrapper

- docs/uperf.md
- resources/crds/ripsaw_v1alpha1_uperf_vm.yaml
- roles/uperf/tasks/main.yml
- roles/uperf/templates/configmap_script.yml.j2
- roles/uperf/templates/server_vm.yml.j2
Tested running up to five uperf VM client-server pairs.
* Add a "client ready" state for VMs to allow for any installation and setup prior to test
* Use SETNX/INCR for both "client ready" and "server ready" to ensure we have an even count before triggering start
* When "blocking client from running uperf", use 'start' key instead of altering server 'ready'
* Increase VM memory requirements to reduce memory pressure during startup
* Add a 1/10s sleep in the "client ready" loop to prevent lock-up
* Changes to match pod uperf test
* VM CPU topology to remain on a single socket
* Uperf test arguments
> Support for uperf multi-pair VM runs

- roles/uperf/templates/workload.yml.j2
This helps in cases where uperf is run at scale (across multiple nodes)
and we want to figure out throughput per worker node. Tis information can
be consumed in the benchmark-wrapper.
> Add node name to environment variables

- docs/metadata.md
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/backpack/templates/backpack.yml
- templates/metadata.yml.j2
Allow ssl verification for elasticsearch in backpack. To enable add ssl: true to the metadata section of the cr.
```
metadata:
ssl: true
```
> Enable ssl verification for Elasticsearch in Backpack

- tests/common.sh
The populate test list function for iperf was incorrectly using iperf-bench instead of iperf.
> Fixing populate function for iperf

- roles/iperf3/templates/client.yml.j2
- roles/iperf3/templates/client_store.yml.j2
- roles/iperf3/templates/server.yml.j2
Add pod anti-affinity rules to place iperf3 client and server benchmark pods on different nodes
> Add Iperf3 pod anti-affinity rules

- docs/fio_distributed.md
- resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
- roles/fio_distributed/templates/configmap.yml.j2
since the behavior of the Ceph compression, we need that the prefill block size will be the same as the tested block size on compressed volumes.
> adding prefill blocksize, used for compressed volumes

- roles/fio_distributed/templates/servers.yaml
W/o this fix, we've detected issues when using nodeselector in a CR like:
```yaml
apiVersion: ripsaw.cloudbulldozer.io/v1alpha1
kind: Benchmark
metadata:
name: etcd-fio
namespace: my-ripsaw
spec:
elasticsearch:
url: https://search-cloud-perf-lqrf3jjtaqo7727m7ynd2xyt4y.us-west-2.es.amazonaws.com
clustername: test_cloud
test_user: test_cloud
metadata:
collection: true
serviceaccount: backpack-view
workload:
name: blablabla
args:
nodeselector:
foo: bar
iodepth: 1
log_sample_rate: 1000
samples: 5
servers: 1
jobs:
- write
bs:
- 2300
numjobs:
- 1
filesize: 50MiB
global_overrides:
- fdatasync=1
- ioengine=sync
```
Using the above CR Benchmark-operator prints the following error
```
"nodeSelector": "foo:bar", …
```
> Add missing space between nodeSelector key and value

- README.md
To add transparency regarding what workloads are CI tested I've added a "CI Tested" column to the ReadMe.
This resolves https://github.com/cloud-bulldozer/benchmark-operator/issues/523
> Add CI tested column to ReadMe

- resources/crds/ripsaw_v1alpha1_byowl_cr.yaml
- resources/crds/ripsaw_v1alpha1_cyclictest_cr.yaml
- resources/crds/ripsaw_v1alpha1_fio_distributed_cr.yaml
- resources/crds/ripsaw_v1alpha1_fio_distributed_vm_cr.yaml
- resources/crds/ripsaw_v1alpha1_fs_drift_cr.yaml
- resources/crds/ripsaw_v1alpha1_hammerdb_cr.yaml
- resources/crds/ripsaw_v1alpha1_hammerdb_index_cr.yaml
- resources/crds/ripsaw_v1alpha1_iperf3_cr.yaml
- resources/crds/ripsaw_v1alpha1_kube-burner_cr.yaml
- resources/crds/ripsaw_v1alpha1_oslat_cr.yaml
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- resources/crds/ripsaw_v1alpha1_uperf_vm.yaml
- roles/cyclictest/templates/cyclictestjob.yaml
- roles/fio_distributed/templates/client.yaml
- roles/fs-drift/templates/workload_job.yml.j2
- roles/oslat/templates/oslatjob.yaml
- roles/pgbench/templates/workload.yml.j2
- roles/scale_openshift/templates/scale.yml
- roles/smallfile/templates/workload_job.yml.j2
- roles/stressng/tasks/main.yaml
- roles/stressng/templates/stressng_workload.yml.j2
- roles/uperf/templates/configmap_script.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/vegeta/templates/vegeta.yml.j2
- roles/ycsb/templates/ycsb_load.yaml
- roles/ycsb/templates/ycsb_run.yaml
Several fixes/changes:
- stressng syntax error issues.
- So work in standardizing our examples.
- Enables `verify_cert` to all workloads wrapped by snafu.
Helps fixing some issues from https://github.com/cloud-bulldozer/benchmark-operator/issues/520
> Standarize examples

- tests/mssql.yaml
Should prevent using the `oc adm policy add-scc-to-group nonroot system:authenticated` workaround for mssql which seems causing other issues.
> Remove runAsUser in mssql

- docs/kube-burner.md
- roles/kube-burner/tasks/main.yml
- roles/kube-burner/templates/node-pod-density.yml.j2
This scenarios is useful when you only care about creating a  lot of
pods in a namespace and don't care about distribution across worker nodes.
This is similar to what used to be called pod-vertical.
> Add pod-density scenarios

- docs/kube-burner.md
- roles/kube-burner/templates/kube-burner.yml.j2
Inject ES as env var. With this commit done in kube-burner https://github.com/cloud-bulldozer/kube-burner/pull/67, we can use environment variables to define the configuration. Adding prom_es  as envvar will allow us to overwrite the ElasticSearch endpoint in jobs using a remote configuration file, hence we can avoid setting ES secrets in the remote configuration file, as they can be configured with this mechanism
> ES env var

- deploy/25_role.yaml
- deploy/35_role_binding.yaml
- docs/uperf.md
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- resources/crds/ripsaw_v1alpha1_uperf_cr.yaml
- resources/operator.yaml
- roles/uperf/tasks/cleanup.yml
- roles/uperf/tasks/init.yml
- roles/uperf/tasks/main.yml
- roles/uperf/tasks/next_set.yml
- roles/uperf/tasks/run_a_set.yml
- roles/uperf/tasks/send_client_run_signal.yml
- roles/uperf/tasks/setup.yml
- roles/uperf/tasks/start_client.yml
- roles/uperf/tasks/start_server.yml
- roles/uperf/tasks/wait_client_done.yml
- roles/uperf/tasks/wait_client_ready.yml
- roles/uperf/tasks/wait_server_ready.yml
- roles/uperf/tasks/wait_set_done.yml
- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/server_vm.yml.j2
- roles/uperf/templates/service.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/uperf/templates/workload_vm.yml.j2
- roles/uperf/vars/main.yml
- tests/test_crs/valid_uperf.yaml
- tests/test_crs/valid_uperf_networkpolicy.yaml
- tests/test_crs/valid_uperf_resources.yaml
- tests/test_crs/valid_uperf_serviceip.yaml
- tests/test_uperf.sh
This PR adds scale mode enhancement to UPERF workload for Telco-5G such as VZ's Webscale where there are up to 250 nodes at the moment.  The scale mode are realized by the following new UPERF CR options
- colocate: true/false
- density_range: [low,high]
- node_range:[ low,high]
- step_size: addN, log2
- exclude_labels: []
See uperf.md for more details.  The following preso is the project status sandbox but you could find a few useful explanations,
https://docs.google.com/presentation/d/11zCqw8K98jams8wYO24ATwpKzNYTK-xuC-gbvAddbLY/edit#slide=id.g78a1e8b739_0_913 
Only support "pod' type.  "VM" type functionality remains unchanged. Future enhancement is being considered
1. Add ability to gather node inventory at run-time to build-up worker node list.
2. Add ability to instantiate the number …
> Add UPERF Scale Mode Telco-5G

- roles/iperf3/templates/client.yml.j2
- roles/iperf3/templates/client_store.yml.j2
- roles/iperf3/templates/server.yml.j2
During iPerf3 network measurements, we have noticed that we have to pass all these following compulsory arguments.
```
transmit_type: time
transmit_value: 60
omit_start: 0
length_buffer: 128K
window_size: 64k
ip_tos: 0
mss: 900
streams: 1
```
As a result it generates the following command-lines for Server and Client POD.
Server POD Command: `iperf3 -s -p 5201 --forceflush`
Client POD Command: `iperf3 -c <IP_ADDRESS> -p 5201 --time 60 -l 128K -P 1 -w 64k -M 900 -S 0 -O 0 -R`
I get better performance with these following simple command-lines:
Server POD Command: `iperf3 -s -p 5201 --forceflush`
Client POD Command: `iperf3 -c <IP_ADDRESS> -p 5201 --time 60 -R`
It would be helpful if we make these compulsory arguments to optional arguments. It will help to reduce search time for default value …
> Remove iperf3 compulsory arguments

- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/service.yml.j2
This PR truncates names to 27 chars. It was discovered that jinja 'truncate' filter does not truncate for less than 5 chars.  So the current code that relies on truncate(32) would not take effect for names with length between 32 to 37 chars. Without truncation, these node names produce UPERF objects with meta.names and labels that exceed 63 chars violating k8s API.
Truncate 5 more chars.
On a cluster that has node names of 37 chars (berrymar19-9wc5t-worker-eastus1-pnfrk) UPERF failed before the fix, but with the fix it works.
> Truncate UPERF node names to 27 chars max.

- charts/benchmark-operator/templates/service-account.yaml
The service account name is hard coded in some of the workload
roles, ie:
https://github.com/cloud-bulldozer/benchmark-operator/blob/master/roles/fio_distributed/templates/servers.yaml#L48
If someone were to change the fullnameOverride in values.yaml the
workload would fail.
> Always use benchmark-operator for service account

- CONTRIBUTING.md
Adding specific operator-sdk version and alternate command in contributing doc. 
NOTE: At the most recent version of operator-sdk (v1.3.0-ocp) `operator-sdk build` is no longer a valid command
> Adding contributing doc version updates

- roles/kube-burner/files/metrics-aggregated.yaml
- roles/kube-burner/files/metrics.yaml
This commit:
- Modifies the metrics profiles used by the kube-burner to capture the
prometheus replicas CPU and Memory usage as the current implementation
only collects the aggregated metrics ( average ) on the infra nodes.
- Also modifies the aggregated queries to include registry and logging
components resource usage on the infra nodes.
> Add more metrics to capture during the kube-burner runs

- README.md
- docs/log_generator.md
- resources/crds/ripsaw_v1alpha1_log_generator_cr.yaml
- roles/log_generator/tasks/main.yml
- roles/log_generator/templates/log_generator.yml
- tests/common.sh
- tests/test_crs/valid_log_generator.yaml
- tests/test_list
- tests/test_log_generator.sh
Adding a log generator workload that will generate X messages of Y size (in bytes) per second/minute over a duration of Z minutes. If provided it will also check the backed log aggregator to confirm it received the expected number of messages. Supported backends are elasticsearch and AWS cloudwatch.
NOTE: This requires a backend storage to be deployed if we want to create a valid ci test for this.
benchmark-wrapper PR: https://github.com/cloud-bulldozer/benchmark-wrapper/pull/254 must be merged prior to this.
> Add log generator workload

- docs/log_generator.md
2 Log generator variables were documented with -'s instead of _'s. This corrects that issue.
> Fixing documented variables to have _'s instead of -'s

- roles/kube-burner/files/app-deployment.yml
- roles/kube-burner/templates/max-namespaces.yml.j2
- roles/kube-burner/templates/node-density-heavy.yml.j2
Using livenessprobes in addition to readinessprobes increases the load
on the kubelet which is what we want with this test.
> Enhance node-density heavy to use livenessprobes

- roles/kube-burner/files/metrics-aggregated.yaml
- roles/kube-burner/files/metrics.yaml
- Add more API metrics to metrics-aggregated.yaml
- Add some comments
- Remove drop packet metrics. We should not use these reports to check for dropped packets. The dashboards provided by dittybopper should be used for this purpose
- Remove kubelet and cri-o metrics from metrics-aggregated.yaml. We don' use them here, these metrics fit better on the metrics.yaml profile (default for node-density)
- Add heap and gc metrics
> API & golang metrics

- docs/byowl.md
- roles/byowl/templates/workload.yml
Currently BYOWL does not allow to run POD in privileged mode, hostPath access, mountPath, etc properties.
Can add support for these and all possible properties in BYOWL, so that we can use BYOWL for any workload which can run in privileged mode and should have access to hostPath etc.
Currently I have hard coded these option in the roles/byowl/templates/workload.yml and building the benchmark-operator myself.
If we add all possible properties support in BYOWL, individual do not need to build the benchmark-operator themselves.
This PR for issue #533
This generic changes does not work for all the options. May be I am missing something.
Detailed discussion: https://github.com/cloud-bulldozer/benchmark-operator/issues/533#issuecomment-799143133
> BYOWL: Suppot for any options under spec and container

- docs/kube-burner.md
- resources/crds/ripsaw_v1alpha1_concurrent_builds_cr.yaml
- roles/kube-burner/files/buildconfig_triggers.yml
- roles/kube-burner/tasks/main.yml
- roles/kube-burner/templates/concurrent-builds.yml.j2
- tests/test_crs/valid_kube-burner.yaml
- tests/test_kubeburner.sh
This creates the start of the objects needed to run the concurrent builds test case. It will create a buildconfig and an image stream in each namespace. Because of the set up of the buildconfig a build and pod will also get created and run during the kube-burner run. 
The addition of starting builds concurrently seemed like too much to add to kube-burner at this time but I would be open to adding it to get the necessary benchmarks we want for this test. 
This is a little different from some of the other workloads in kube-burner because it just creates builds to later be used to start concurrent builds using the workloads/kube-burner/run_concurrentbuilds_test_fromgit.sh script in e2e-benchmarking. 
Not sure if the resources/crds/ripsaw_v1alpha1_concurrent_builds_cr.yaml file is necessary, …
> Adding concurrent builds to benchmark operator

- README.md
- docs/image_pull.md
- roles/image_pull/tasks/main.yml
- roles/image_pull/templates/image_pull.yml
- tests/common.sh
- tests/test_crs/valid_image_pull.yaml
- tests/test_image_pull.sh
Depends-On: https://github.com/cloud-bulldozer/benchmark-wrapper/pull/264
Adding Image Pull workload which takes a list of images to pull and X pod's to do them. It then coordinates each image to be pulled by the pod at roughly the same time (within a few second margin of error). It can then display and index the resultant data around timings, retries, etc.
> Adding Image Pull workload

- CONTRIBUTING.md
- resources/crds/ripsaw_v1alpha1_ripsaw_crd.yaml
- roles/cerberus/tasks/main.yml
Signed-off-by: Kedar Vijay Kulkarni <kkulkarni@redhat.com>
Cerberus may not always be running with valid certs when it is setup as an ephemeral instance, and it would be useful to provide ability to pass `validate_certs` parameter to the `uri` call. 
Extends CRD to add new boolean for `cerberus_validate_certs` and extends the role to accept that variable. It is being set to `false` as default as its more likely what users would want in my experience. URI Module defaults to `true` otherwise. 
CC:  @mffiedler 
Please review @chaitanyaenr
> adding cerberus validate certs parameter

- docs/log_generator.md
- roles/log_generator/templates/log_generator.yml
This along with https://github.com/cloud-bulldozer/benchmark-wrapper/pull/273
helps suppress any unneeded logging in the pod, so that we can accurately and easily count
the number of log emssages recevied in a backend like kafka merely by using the offsets.
The plan is to deploy the log generator pods in a separate namespace and forward those logs
to a topic in kafka. That way we would be able to reliably count the messages received just
by looking at kafka topic offset. Otherwise there would be other logs from the log generator pods
as well as benchmark-operator pod that would make it hard to reliably count logs received just by
kafka offset.
> Quiesce logging in pod for log generator workload

- roles/kube-burner/templates/max-services.yml.j2
Shorten max-services to max-serv to avoid line length issue. Can now successfully create 5000 services in a single namespace.
> Shorten max-services to max-serv to avoid line length issue

- docs/cache_dropping.md
- roles/ceph_osd_cache_drop/ocs-cache-drop-clusterrole.yaml
add an RBAC YAML that permits cache dropping role to detect cache dropper pod and toolbox pod in openshift-storage namespace.   Tell OSD cache dropping users to use this YAML.   A similar thing had to be done for the kernel cache dropper.  
benchmark-operator got HTTP 403 access denied errors from K8S trying to detect pods running in openshift-storage namespace.
> Osd cache drop rbac

- roles/kube-burner/files/metrics-aggregated.yaml
- roles/kube-burner/files/metrics.yaml
Updating namespace count query since that metric is no longer being scraped in OpenShift. Context at https://github.com/openshift/cluster-monitoring-operator/pull/1141
> Update namespace count query

- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/server_vm.yml.j2
- roles/uperf/templates/service.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/uperf/templates/workload_vm.yml.j2
Adding labels to resources created by benchmark-operator to more easily identify them during benchmark run.
Will end up adding these to the other workloads.
> Add uperf resource labels

- playbooks/benchmark.yml
- roles/uuid/tasks/main.yml
An error like this one is printed as soon as a new Benchmark is created, the code change proposed here should fix it.
```
--------------------------- Ansible Task StdOut -------------------------------
TASK [set_fact] ******************************** 
fatal: [localhost]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'uuid'\n\nThe error appears to be in '/opt/ansible/playbooks/benchmark.yml': line 61, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - set_fact:\n    ^ here\n" 
```
> Fix uuid error

- watches.yaml
We need to set reconcilePeriod as low as possible. As there are reconcile actions that does not modify the status of the Benchmark CR (modifying the Benchmark object triggers a reconcile),  (I observed this behaviour in the uperf benchmark), the benchmark-operator could wait up to 1 minute to perform the next actions of that Benchmark.
With this change we should dramatically drop the benchmark duration.
> Lower reconcilePeriod

- roles/system-metrics/tasks/main.yml
- roles/system-metrics/templates/kube-burner.yml.j2
- roles/system-metrics/templates/node-metrics.yml
The current implementation of system-metrics was broken due to recent changes in kube-burner's metrics-collection config structure.
> Fix system-metrics collection

- playbooks/templates/metadata.yml.j2
- roles/backpack/templates/backpack.yml
ACS sets a security context constraint (SCC) that is more restrictive than the SCC that previously applied to backpack when it was deployed as an initContainer for kube-burner. Some more background on this [here](https://bugzilla.redhat.com/show_bug.cgi?id=1942725) and [here](https://coreos.slack.com/archives/CNKHL6076/p1626366399496100).
Backpack i.e. stockpile needs a RW root, so this change sets that explicitly in the container specs for backpack.
Tested similar changes against v0.1 where it [passed](http://gavin-stackrox-rhacs-airflow.apps.sailplane.perf.lab.eng.rdu2.redhat.com/graph?dag_id=4.7_aws_rhacs2&run_id=manual__2021-07-22T14%3A37%3A05.791476%2B00%3A00&execution_date=2021-07-22+14%3A37%3A05.791476%2B00%3A00) (previously cluster_density would …
> Backpack needs a RW root

- Makefile
We shouldn't append the architecture when IMG is set.
With the previous implementation, executing `$ make image-build IMG=quay.io/bla/blabla:latest`
Ended up with the image `quay.io/bla/blabla:latest-amd64` being built and pushed, which is incorrect, we shouldn't append the architecture suffix when IMG is set.
> Use IMG to push the image

- Makefile
- hack/tag_name.sh
Turns out that the `--show-current` flag of the `git branch` subcommand is not available in old git versions.
```
git describe --tags 2>/dev/null || git rev-parse --abbrev-ref HEAD | sed 's/master/latest/g'
```
If the first command works, means we're in a tag, otherwise, we're in a branch.
cc: @kedark3
> --show-current flag is not available for git versions < 2.22

- roles/fio_distributed/templates/configmap.yml.j2
move numjobs loop up above prefill section
pass numjobs var into prefill fio job file
This fixes problem where fio reported read throughput greater than the actual block device throughput that fio was reading.   The root cause was that the files were not completely populated so that reads to the unwritten portions of the file return immediately with zeroes, resulting in higher throughput from the files than the block device.
> fio prefill should use same numjobs value as fio samples

- roles/smallfile/templates/smallfilejob.other_parameters.yaml.j2
- tests/test_crs/valid_smallfile.yaml
allows delay after cleanup operation to give Cephfs provisioner time to clean up files in deleted Cephfs PVs
higher-than-expected variance in smallfile samples
also add test coverage for full set of smallfile parameters.
> Smf cleanup delay

- .github/workflows/release.yml
- Makefile
Make the variable IMAGE_ARCH optional. By default the containers built, pushed and deployed don't not have the the -$(ARCH) suffix. Passing IMAGE_ARCH to Makefile adds this suffix
The release workflow has been updated to pass this variable.
> Remove IMG_ARCH references

- roles/kube-burner/templates/kube-burner.yml.j2
Changes the kube-burner container config by disabling the readonlyfilesystem option. This is required to create a pprof-directory on the container.
@rsevilla87
> Disable readonly fs in kube-burner pod

- CONTRIBUTING.md
- Makefile
- README.md
- config/manager/kustomization.yaml
- config/samples/iperf3/cr.yaml
- docs/cyclictest.md
- docs/elastic.md
- docs/fio_distributed.md
- docs/flent.md
- docs/fs-drift.md
- docs/iperf3.md
- docs/oslat.md
- docs/smallfile.md
- docs/sysbench.md
- docs/uperf.md
- docs/ycsb.md
Some of the links in the docs were fixed previously by https://github.com/cloud-bulldozer/benchmark-operator/pull/616, however, there was a few misses.
Some of the docs were inconsistent in their sample sections.
Discovered while taking a look at https://github.com/cloud-bulldozer/benchmark-operator/issues/642.
- Small change to comment out length of buffer in iperf3 test, as 128K is the default for TCP but hardcoding the value breaks UDP.
- Minor corresponding changes to docs.
> Small CR iperf3 CR change & docs update

- docs/cache_dropping.md
get rid of a now-unnecessary step
explain better how to set labels for kernel cache dropper
> update cache dropping doc

- roles/hammerdb/tasks/main.yaml
- roles/hammerdb/templates/db_mariadb_workload_vm.sh.j2
- roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
- roles/hammerdb/templates/db_postgres_workload_vm.sh.j2
- roles/stressng/templates/stressng_workload_vm.yml.j2
- roles/uperf/templates/configmap_script.yml.j2
Benchmark-runner: CNV CI: Fix VM complete state for Stressng, Uperf, Hammerdb 
Stressng - adding {{ trunc_uuid }} to roles/stressng/templates/stressng_workload_vm.yml.j2
Uperf - adding {{ trunc_uuid }} to roles/uperf/templates/configmap_script.yml.j2
hammedb - adding back VM section to roles/hammerdb/tasks/main.yaml and add {{ trunc_uuid }} to the following:
roles/hammerdb/templates/db_mariadb_workload_vm.sh.j2
roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
roles/hammerdb/templates/db_postgres_workload_vm.sh.j2
Those fixes already tested and verified by benchmark-runner framework
Please merge it ASAP to make benchmark-runner CNV CI pass. [https://github.com/redhat-performance/benchmark-runner/actions/runs/1151747467](benchmark runner CI)
> fix vm complete state

- config/samples/sysbench/cr.yaml
- docs/sysbench.md
- roles/sysbench/templates/workload.yml
Enable running the sysbench test on specific node specifying a `pin_node` parameter in the cr.
Close #661
> Able to run the sysbench test on a specific node

- roles/byowl/templates/workload.yml
- roles/flent/templates/workload.yml.j2
- roles/hammerdb/templates/db_creation.yml
- roles/hammerdb/templates/db_mariadb_workload.yml.j2
- roles/hammerdb/templates/db_mssql_workload.yml.j2
- roles/hammerdb/templates/db_postgres_workload.yml.j2
- roles/iperf3/templates/client.yml.j2
- roles/iperf3/templates/client_store.yml.j2
- roles/iperf3/templates/server.yml.j2
- roles/pgbench/templates/workload.yml.j2
- roles/stressng/templates/stressng_workload.yml.j2
- roles/sysbench/templates/workload.yml
- roles/testpmd/templates/testpmd.yml.j2
- roles/testpmd/templates/trex.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/vegeta/templates/vegeta.yml.j2
Our jobs must be one shot, and we should keep failed or completed pods to ease debugging.
Restart policy must be set to Never to prevent garbage collecting failed pods, more info at https://github.com/kubernetes/kubernetes/issues/74848#issuecomment-475178355
> Set restartPolicy Never to all jobs deployed by benchmark-operator

- config/crd/bases/ripsaw.cloudbulldozer.io_benchmarks.yaml
- roles/cyclictest/templates/cyclictestjob.yaml
- roles/fio_distributed/templates/client.yaml
- roles/flent/templates/workload.yml.j2
- roles/fs-drift/templates/workload_job.yml.j2
- roles/hammerdb/templates/db_mariadb_workload.yml.j2
- roles/hammerdb/templates/db_mariadb_workload_vm.sh.j2
- roles/hammerdb/templates/db_mssql_workload.yml.j2
- roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
- roles/hammerdb/templates/db_postgres_workload.yml.j2
- roles/hammerdb/templates/db_postgres_workload_vm.sh.j2
- roles/image_pull/templates/image_pull.yml
- roles/log_generator/templates/log_generator.yml
- roles/oslat/templates/oslatjob.yaml
- roles/pgbench/templates/workload.yml.j2
- roles/scale_openshift/templates/scale.yml
- roles/smallfile/templates/workload_job.yml.j2
- roles/stressng/templates/stressng_workload.yml.j2
- roles/stressng/templates/stressng_workload_vm.yml.j2
- roles/testpmd/templates/trex.yml.j2
- roles/uperf/templates/configmap_script.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/vegeta/templates/vegeta.yml.j2
- roles/ycsb/templates/ycsb_load.yaml
- roles/ycsb/templates/ycsb_run.yaml
With this change, elasticsearch indexing is enabled when the elasticsearch.url parameter is filled with something different from ""
The current implementation is not possible to disable ES indexing since the elasticsearch dictionary defaults to {}
> Elasticsearch URL

- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/service.yml.j2
Internally UPERF benchmark task(s) may truncate a node name and combine it with a suffix to create other name(s) for internal use.  The truncation is based on a fixed length and hence could result in the truncated portion ended with a dot '.' character. Subsequently the combined name may be an illegal name e.g. "abc.-0-suffix" per RFC 1123
During truncation if the corner case happens, truncate one more char to trim off the dot.
The diff works on local unit-test and on the original system reported  by issue #644
> UPERF: Fix node name truncation to avoid ending with a dot  '.' char

- roles/backpack/tasks/main.yml
Workloads using not targeted metadata collection are not working since the latest changes pushed into the backpack role. The condition https://github.com/cloud-bulldozer/benchmark-operator/blob/9826c52bd02ec21302e656155fcb3d2369de00c4/playbooks/benchmark.yml#L100
is never met since the backpack role sets status.state regardless it's running a purely backpack workload or not, we need to set it only when running a standalone backpack workload.
cc: @kedark3 
Workloads using daemonset based metadata collection.
> Fix not targeted metadata collection

- docs/fio_distributed.md
- roles/fio_distributed/templates/configmap.yml.j2
- tests/test_crs/valid_fiod_bsrange.yaml
- tests/test_crs/valid_fiod_hostpath.yaml
do not merge yet, in process of running fio CI tests, but tested this on a small scale
This PR turns off histogram logging by default, while allowing the user to turn it back on for later development
This shrinks the amount of log data being fetched by fio-client pod, hopefully reducing chance of fio inflate error
> Fio no log hist

- config/samples/vegeta/cr.yaml
- docs/vegeta.md
- roles/vegeta/templates/vegeta.yml.j2
Currently vegeta pods can run on any node. This PR allows to specify a node selector in the vegeta benchmarks.
N/A, new feature
> Add a nodeSelector for vegeta pods

- roles/smallfile/templates/smallfilejob.other_parameters.yaml.j2
- tests/test_crs/valid_smallfile.yaml
add support for cleanup_delay_usec_per_file CR parameter 
should have been in last PR but I missed
change the CI to actually test it
> Cleanup delay pass to smf

- .github/workflows/e2e.yml
Limits concurrency to one in e2e workflow to prevent conflicts.
> Concurrency for e2e workflow

- docs/e2e-ci.md
- roles/scale_openshift/templates/scale.yml
Current execution always ends with exit 0 after sleep runs.
Executing sh with -e will exit if run_snafu fails capturing its exit code
```
[morenod@morenod-laptop ~]$ sh -e -c "echo 1 ; echo 0"
1
0
[morenod@morenod-laptop ~]$ sh -e -c "false ; echo 0"
[morenod@morenod-laptop ~]$ sh -e -c "true ; echo 0"
0
[morenod@morenod-laptop ~]$ 
```
Fixes #692
> update sleep execution after scale tu capture run_snafu exit code correctly

- roles/api_load/templates/api_load.yml
- roles/image_pull/templates/image_pull.yml
imagePullPolicy was misaligned and caused it to be ignored.
New images for the image pull and api-load workload were not being pulled
> Fix indentation on image pull policy

- roles/fs-drift/tasks/main.yml
- roles/fs-drift/templates/workload_job.yml.j2
- roles/hammerdb/templates/db_mariadb_workload.yml.j2
- roles/hammerdb/templates/db_mssql_workload.yml.j2
- roles/hammerdb/templates/db_postgres_workload.yml.j2
- roles/iperf3/templates/client_store.yml.j2
- roles/pgbench/defaults/main.yml
- roles/smallfile/tasks/main.yml
- roles/smallfile/templates/workload_job.yml.j2
Depends-On: https://github.com/cloud-bulldozer/benchmark-wrapper/pull/396
Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>
image tags are pointing to master as default. But master tag is not being built when a new version is deployed, changing it to latest.
> Standardizes using latest tag for images

- roles/oslat/files/oslat.sh
oslat doesn't have a --runtime parameter (anymore?), but a --duration instead:
```
This is an OS latency detector by running busy loops on specified cores.
Please run this tool using root.
Available options:
-b, --bucket-size      Specify the number of the buckets (4-1024)
-B, --bias             Add a bias to all the buckets using the estimated mininum
-c, --cpu-list         Specify CPUs to run on, e.g. '1,3,5,7-15'
-C, --cpu-main-thread  Specify which CPU the main thread runs on.  Default is cpu0.
-D, --duration         Specify test duration, e.g., 60, 20m, 2H
(m/M: minutes, h/H: hours, d/D: days)
-f, --rtprio           Using SCHED_FIFO priority (1-99)
-m, --workload-mem     Size of the memory to use for the workload (e.g., 4K, 1M).
Total memory usage will be this value multiplies 2*N, …
```
> oslat runtime parameter fix

- roles/api_load/templates/api_load.yml
When running a full load test this made the
process undergo a forced termination.
Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>
> Changing activeDeadlineSeconds default for api_load

- config/samples/fio/vm-cr.yaml
- docs/fio_distributed.md
- roles/fio_distributed/templates/server_vm.yml.j2
Adjusting server_vm config so that any VM containerDisk image can be used since the workload is run from chroot into a fio container image (i.e. no custom VM images need to be maintained).
Also adding a fallback VM option if no PVC/HostDisk is specified, use an emptyDisk (ephemeral storage).
Adding nodeSelector support for VMs.
#527
> Fio server_vm image updates

- cli/setup.cfg
Missing Python package for the Ripsaw CLI in a fresh 3.10 venv.
Fixes #716
> Add dateutil and requests as deps for CLI setup.cfg

- config/manager/manager.yaml
In smaller deployments (not number of nodes, but number of cores), I
have seen where the operator will not deploy.
Additionally, setting the limit to 2, kustomize will set requests to 2.
> Add CPU resource request to kutomize manifest

- roles/cyclictest/tasks/main.yml
- roles/cyclictest/templates/cyclictestjob.yaml
- roles/oslat/tasks/main.yml
- roles/oslat/templates/oslatjob.yaml
If the benchmarks get launched via airflow, the UUID the combination of {{ ansible_operator_meta.name }}-workload-{{ trunc_uuid }} gets too long (> 63 chars)
Shortened the names to <benchmark_name>-{{ trunc_uuid }}
> shortening job names for cyclictest and oslat

- roles/cyclictest/templates/cyclictestjob.yaml
- roles/oslat/templates/oslatjob.yaml
Changing the names isn't enough, the corresponding configmaps need to be changed too.
configmap names for oslat and cyclictest
> fixing configmap names

- charts/benchmark-operator/templates/operator.yaml
The helm chart was missing a label, which was causing issues with deploy
UPerf. Fixing the template.
Signed-off-by: Joe Talerico <rook@isovalent.com>
> Helm Chart missing label

- docs/uperf.md
- e2e/013-uperf.bats
- e2e/uperf/uperf_serviceip_nodeport.yaml
- roles/uperf/tasks/start_client.yml
- roles/uperf/tasks/start_server.yml
- roles/uperf/templates/configmap.yml.j2
- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/server_vm.yml.j2
- roles/uperf/templates/service_metallb.yml.j2
- roles/uperf/templates/workload.yml.j2
- tests/test_crs/valid_uperf_serviceip_nodeport.yaml
- tests/test_uperf.sh
To support different service types for uperf workload
NodePort: 
```
serviceip: true
servicetype: "nodeport"
```
Loadbalancer: only tested for `metallb` loadbalancers on baremetal.
```
serviceip: true
servicetype: "metallb"
metallb:
addresspool: "addresspool-l3"
service_etp: "Cluster"
```
@rsevilla87 and @josecastillolema  I've updated the uperf server to listen on port `30000` for all service types as advised, that avoids complexity in the code.
> Uperf workload with nodeport and loadbalancer type svc

- image_resources/centos8-appstream.repo
CentOS 8 is now EOL, so moving to vault for now.
> Update AppStream Repo for CentOS 8

- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/workload.yml.j2
`macro` is not passing all current variables to the `include`'d template, so `metadata` dict was always undefined and job definition was missing `initContainers` section. Replaced that with regular `include` with `filter` to indent properly
I could see it includes `metadata.yml` on both server and client pod definition now,
```
...
initContainers:
- args:
- |
python3 stockpile-wrapper.py -s=https://search-perfscale-dev-chmf5l4sh66lvxbnadi4bznl3a.us-west-2.es.amazonaws.com:443 -u=13a31b07-4c90-535f-90cd-37c8bda42c8b -n=${my_node_name} -N=${my_pod_name} --redisip=10.129.40.107 --redisport=6379 --tags=common,k8s,openshift
command:
- /bin/sh
- -c
...
```
#725
> corrected indentation with `filter`

- roles/uperf/templates/workload.yml.j2
Recent PR #735 had an issue in formatting the client_pod.yml when creating multi pair + pin uperf pods.
#737
> patching client pod indentation

- cli/ripsaw/clients/k8s.py
- image_resources/centos8-appstream.repo
If http_proxy is in ENV, add proxy and proxy_headers to kubernetes.client.
example of the ENV variable:
http_proxy=http://<user>:<password>@<proxy_host>:<port>
https://github.com/cloud-bulldozer/benchmark-operator/issues/726
> add proxy to k8s client if it exists in env

- roles/hammerdb/templates/db_mssql_workload_vm.sh.j2
Firewall-cmd fails in cloud-init in centos stream8
Use firewall-offline-cmd instead of Firewall-cmd
> fix firewall for centos stream8

- config/samples/hammerdb/mariadb/vm-cr.yaml
- config/samples/hammerdb/mssql/vm-cr.yaml
- config/samples/hammerdb/postgres/vm-cr.yaml
- config/samples/hammerdb/vm-cr.yaml
Update hammerdb samples from centos8 to centos-stream8
Update the following hammerdb container disks in the following databases:
1. Mssql
2. Postgresql
3. Mariadb
> update hammerdb vm samples to centos stream8

- e2e/fs_drift/fs_drift.yaml
- e2e/fs_drift/fs_drift_hostpath.yaml
- roles/fs-drift/templates/other_parameters.yaml.j2
- tests/test_crs/valid_fs_drift.yaml
- tests/test_crs/valid_fs_drift_hostpath.yaml
- tests/test_fs_drift.sh
Do not merge yet...
change test parameters so that response time stats reach elastic search
addresses issue #741
> Fs drift test captures response time stats

- cli/ripsaw/models/benchmark.py
This will prevent ugly and useless traceback messages like:
```
2022-04-01, 13:11:52 EDT] {subprocess.py:89} INFO - Traceback (most recent call last):
[2022-04-01, 13:11:52 EDT] {subprocess.py:89} INFO -   File "/tmp/ripsaw-cli/bin/ripsaw", line 33, in <module>
[2022-04-01, 13:11:52 EDT] {subprocess.py:89} INFO -     sys.exit(load_entry_point('ripsaw-cli==0.0.1', 'console_scripts', 'ripsaw')())
[2022-04-01, 13:11:52 EDT] {subprocess.py:89} INFO -   File "/tmp/ripsaw-cli/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
[2022-04-01, 13:11:52 EDT] {subprocess.py:89} INFO -     return self.main(*args, **kwargs)
[2022-04-01, 13:11:52 EDT] {subprocess.py:89} INFO -   File …
```
> Improve cli exeption handling

- e2e/api_load/api_load.yaml
- roles/api_load/templates/api_load.yml
Signed-off-by: Vicente Zepeda Mas <vzepedam@redhat.com>
Updating api-load to match latest [release](https://github.com/cloud-bulldozer/ocm-api-load/releases/tag/v0.3.2)
- Removes extra step to upload to elastic since now it's done within
ocm-api-load
- Adds flags to use elastic search indexing within ocm-api-load
> Updating api-load to match latest release

- cli/tests/clients/test_k8s.py
- cli/tests/resources/job.yaml
There was a race condition in the tests. We where counting the number of pods while an old pod was still in Deleting stage.
Fixes: https://github.com/cloud-bulldozer/benchmark-operator/issues/749
> Fix tests race condition

- e2e/013-uperf.bats
- playbooks/templates/metadata.yml.j2
- playbooks/templates/metadata_pod.yml.j2
- roles/byowl/templates/workload.yml
- roles/cyclictest/templates/cyclictestjob.yaml
- roles/fio_distributed/templates/servers.yaml
- roles/flent/templates/server.yml.j2
- roles/flent/templates/workload.yml.j2
- roles/fs-drift/templates/workload_job.yml.j2
- roles/iperf3/templates/client.yml.j2
- roles/iperf3/templates/server.yml.j2
- roles/kube-burner/templates/kube-burner.yml.j2
- roles/oslat/templates/oslatjob.yaml
- roles/scale_openshift/templates/scale.yml
- roles/smallfile/templates/workload_job.yml.j2
- roles/testpmd/templates/testpmd.yml.j2
- roles/testpmd/templates/trex.yml.j2
- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/workload.yml.j2
- roles/vegeta/templates/vegeta.yml.j2
Rather than setting serviceAccountName: benchmark-operator in every YAML, let's use the metadata template to set it.
> Template serviceAccountName

- Makefile
- hack/tag_name.sh
The original implementation is problematic, i.e: https://github.com/cloud-bulldozer/benchmark-operator/issues/787
The current mechanism to get the tag name doesn't work well. When a new commit lands to the master branch, the master branch is not named correctly
i.e:
```
rsevilla@wonderland /tmp/foo (master) $ git describe --tags 2>/dev/null || git rev-parse --abbrev-ref HEAD | sed 's/master/latest/g'
v1.0.0-1-g487fada
rsevilla@wonderland /tmp/foo (master) $ git log --oneline | head
487fada Foo
12701a6 Added exit status for uperf failures (#782)
94005cd missing env var num_pairs (#784)
```
Some tests I've done:
```shell
rsevilla@wonderland /tmp/foo (master) $ hack/tag_name.sh
latest
rsevilla@wonderland /tmp/foo (master) $ git checkout …
```
> Fix mechanism to get current tag name

- roles/uperf-scale/templates/configmap.yml.j2
- roles/uperf/templates/configmap.yml.j2
Context: https://github.com/cloud-bulldozer/benchmark-operator/issues/780
Assigning a different port for the reverse test so that it doesn't conflict with the forward test port.
> fixing port conflict for uperf bidrec test

- roles/fio_distributed/tasks/main.yml
With FIO we need to wait for server pods to be annotated with IP
addresses. This fix adds that wait.
closes #789
Signed-off-by: Joe Talerico <jtaleric@redhat.com>
> Race condition in FIO

- docs/uperf.md
- roles/uperf/tasks/main.yml
- roles/uperf/templates/server.yml.j2
- roles/uperf/templates/workload.yml.j2
Use podAntiaffinity rules to place uperf client pods in different worker
nodes where the servers are running on
Use podAffinity rules to place all client and server pods in the same node, useful when running more than one pair
All client pods will be scheduled in the same node and servers in another
> Use uperf pod antiAffinity rules

- config/manager/manager.yaml
Let's try to take more advantage of the workload node by setting benchmark-operator's affinity to preferably be scheduled on workload nodes.
I think we should hardcore it, as it doesn't affect the default behavior
> Benchmark-operator's affinity preference to workload node

- roles/hammerdb/templates/db_postgres_workload_vm.sh.j2
Disable autovacuum for improving PostgreSQL performance
1. Adding autovacuum = off:
The hammerdb framework has a setting for PostgreSQL where we can specify that manual vacuuming should be done after every sample … we currently have it disabled, I’m seeing if enabling it (and disabling auto vacuuming which can kick in at random times) will give us consistent performance while also keeping dead tuples under control (too many dead tuples slow down query performance)
** Already tested and Fixed in benchmark-runner [Pod](https://github.com/redhat-performance/benchmark-runner/blob/bc1b7fffb0f8e4d5c19c7d981c9d958538cc2527/benchmark_runner/common/template_operations/templates/hammerdb/internal_data/postgres_template.yaml#L77), case to huge improvement, need to fix it also in VM
2. Removing …
> disable hammerdb postgreSQL autovacuum

- config/samples/stressng/cr.yaml
- roles/stressng/templates/jobfile.j2
stress-ng has many [cpu methods](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux_for_real_time/8/html/optimizing_rhel_8_for_real_time_for_low_latency_operation/assembly_stress-testing-real-time-systems-with-stress-ng_optimizing-rhel8-for-real-time-for-low-latency-operation) for testing. To expose this spec, this PR add cpu method in the CR and jobfile.
> stress-ng: expose cpu method in cr

- roles/fio_distributed/tasks/main.yml
- roles/fio_distributed/templates/client.yaml
- roles/fio_distributed/templates/prefill-client.yaml.j2
- roles/fio_distributed/templates/prefill-configmap.yml.j2
This PR adds a `Prefilling` state to the FIO benchmark.  Previously prefilling and running the actual benchmark were both under the state of `Running`, with this PR the actual benchmark is running during the `Running` state, and prefilling during the `Prefilling` state.
This update has not been tested using `kind: vm`.
> FIO Prefill State

- config/samples/sysbench/cr.yaml
- docs/sysbench.md
- roles/sysbench/tasks/main.yml
- roles/sysbench/templates/sysbench.sh.j2
- roles/sysbench/templates/workload.yml
This PR adds the ability to run sysbench in a CR defined SC.  If a SC is not provided, the volume defaults to `emptyDir` type, as it was doing previously.
It also adds the ability to define options for each phase of `fileio` test.  The current `parameters` act as global parameters, and then it breaks out into `<prepare/run/cleanup>_parameters` that override the global parameters, if you want to remove a global parameter from a phase of the test, providing `null` for the option in the YAML file achieves this.
Adds CR defend SC selection for sysbench.
Creates PVC for the selected SC with CR defined size for sysbench.
> Added StorageClass support to Sysbench

- roles/log_generator/templates/log_generator.yml
e2e-benchmarking allow to select the index_name to use as ES_BACKEND_INDEX.
But this parameter is not managed on the template so it is never used.
Adding it to the template
> Add es_index parameter to log-generator workload template as it can be set on e2e-benchmarking as ES_BACKEND_INDEX

- roles/iperf3/templates/client.yml.j2
In the case of a dual-stack cluster, when ipv6 traffic is required, and even the '-6' option is provided, the 'iperf3 -c ' command will always use an ipv4 address.
The openshift preference in the case of dual-stack is always ipv4. And this is a reason the server pod will always have ipv4 as a main pod address (podIP value).
As a result, when '-6' option is used in this case and 'iperf3 -c ' will run to the ipv4 address, the pod execution fails.
switch to the item.status.podIPs list handling instead of item.status.podIP when ipv6 is required
> iPerf: work-around for ipv6 traffic type on dual-stack cluster

- roles/fio_distributed/tasks/main.yml
1. add storageClassName in "spec" section for PVC
2. remove volume.beta.kubernetes.io/storage-class from annotations section
- [x ] Bug fix
- [x ] Optimization
PVC created via benchmark-operator miss `storageClassName` in `spec` section what causes issues for some of tests which expect `storageClassName` to be present there.
> add storageClassName in "spec" section for PVC

- roles/uperf/templates/workload.yml.j2
Pod affinity to keep server and client within same zone to avoid external variability.
> zone affinity for uperf clients

- docs/stressng.md
```
looking for "jobfile.j2" at "/opt/ansible/roles/stressng/templates/jobfile.j2"
File lookup using /opt/ansible/roles/stressng/templates/jobfile.j2 as file
fatal: [localhost]: FAILED! => {
"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'cpu_method'. 'dict object' has no attribute 'cpu_method'. 'dict object' has no attribute 'cpu_method'. 'dict object' has no attribute 'cpu_method'\n\nThe error appears to be in '/opt/ansible/roles/stressng/tasks/main.yaml': line 4, column 5, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n  - name: template stressng config file\n    ^ here\n"
}
```
- Closes #
- Please describe the System Under Test.
- Please …
> Update stressng.md to reflect crd requirements

- roles/fio_distributed/templates/configmap.yml.j2
- roles/fio_distributed/templates/prefill-configmap.yml.j2
- [ X] Bug fix
When running VM fio workloads with pvcvolumemode=Block, there are issues causing the prefill and client jobs to fail with the following errors:
```
2024-12-12T14:21:07Z - INFO     - MainProcess - wrapper_factory: identified fio as the benchmark wrapper
2024-12-12T14:21:07Z - INFO     - MainProcess - trigger_fio: Executing fio --client=/tmp/host/hosts /tmp/fiod-d7d253e8-b6f5-5969-a1f7-6800708af821/fiojob-randwrite-4KiB-4/1/randwrite/fiojob --output-format=json --output=/tmp/fiod-d7d253e8-b6f5-5969-a1f7-6800708af821/fiojob-randwrite-4KiB-4/1/randwrite/fio-result.json
2024-12-12T14:21:08Z - ERROR    - MainProcess - trigger_fio: Fio failed to execute
2024-12-12T14:21:08Z - ERROR    - MainProcess - trigger_fio: Output file: <fio-server-6-d7d253e8> fio: output file open error: No …
```
> Fix problem when running VM fio workloads using pvcvolumemode=Block

- config/samples/fio/cr.yaml
- config/samples/fio/vm-cr.yaml
- docs/fio_distributed.md
- roles/fio_distributed/templates/client.yaml
- roles/fio_distributed/templates/configmap.yml.j2
- [X ] New feature
**Add support for workload loops with varying iodepth values**
This commit introduces a feature that allows running workload loops using a list of `iodepth` values. By enabling this functionality, users can configure and execute multiple iterations of a workload, each with a different `iodepth`, providing greater flexibility and detailed insights into performance behavior under varying queue depths.
**Key Changes:**
- Modified the workload configuration to accept a list of `iodepth` values.
- Updated logic to iterate through each `iodepth` value and execute workloads accordingly.
- Ensured compatibility with existing configurations to avoid breaking changes.
- Closes #
- [ X] I have performed a self-review of my code.
- Please describe the System Under …
> Add a feature to enable workload loops with varying iodepth values

- roles/uperf-scale/templates/workload.yml.j2
- roles/uperf/templates/workload.yml.j2
…works
- [ X] Bug fix
There is a typo in the code when selecting the IP address of the pods while working with Multus networks. The filter used is `k8s.v1.cni.cncf.io/networks-status`, which is invalid. The correct filter should be `k8s.v1.cni.cncf.io/network-status`.
Additionally, the correct naming for the uperf clients has been implemented, ensuring the IP address of the uperf server in the Multus network is properly selected.
- Closes #
- [X ] I have performed a self-review of my code.
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.
> Fix issues when running uperf and uperf-scale modules with multus networks

- config/samples/fio/vm-cr.yaml
- roles/fio_distributed/templates/server_vm.yml.j2
- [ X] New feature
Currently, when running FIO in VMs, we install software like Podman. In restricted environments, internet access may require a proxy. This update introduces a new parameter that allows setting a proxy environment variable, ensuring compatibility with such environments
- Closes #
- [X ] I have performed a self-review of my code.
- Please describe the System Under Test.
- Please provide detailed steps to perform tests related to this code change.
- How were the fix/results from this change verified? Please provide relevant screenshots or results.
> Add proxy support for FIO in VMs
